from __future__ import annotations

import os
import tornado.web

from . import (
    error,
    fave,
    help,
    info,
    key_management,
    ldetect,
    listener,
    locale,
    main,
    manifest,
    playlist,
    power_hours,
    rating,
    request,
    search,
    streamer,
    sync,
    tip_jar,
    tune_in,
    vote,
)
from .admin import (
    cooldown as admin_cooldown,
    dj as admin_dj,
    dj_election as admin_dj_election,
    donations as admin_donations,
    enable_perks as admin_enable_perks,
    groups as admin_groups,
    js_errors as admin_js_errors,
    power_hours as admin_power_hours,
    producers as admin_producers,
    request_line as admin_request_line,
    scan_errors as admin_scan_errors,
    song_request_only as admin_song_request_only,
    update_user_avatar as admin_update_user_avatar,
    update_user_nickname as admin_update_user_nickname,
    user_search as admin_user_search,
)
from .admin_web import (
    cooldown as admin_web_cooldown,
    developer as admin_web_developer,
    dj_election as admin_web_dj_election,
    donations as admin_web_donations,
    groups as admin_web_groups,
    index as admin_web_index,
    js_errors as admin_web_js_errors,
    power_hours as admin_web_power_hours,
    producers as admin_web_producers,
    scan_errors as admin_web_scan_errors,
    song_request_only as admin_web_song_request_only,
)
from .auth import (
    debug as auth_debug,
    discord as auth_discord,
    login as auth_login,
    logout as auth_logout,
    tos_privacy as auth_tos_privacy,
)

request_classes = [
    (r"/api4/?", help.IndexRequest),
    (r"/api4/help/?", help.IndexRequest),
    (r"/api4/help/(.+)", help.HelpRequest),
    (
        r"/static/(.*)",
        tornado.web.StaticFileHandler,
        {"path": os.path.join(os.path.dirname(__file__), "..", "static")},
    ),
    (
        r"/beta/static/(.*)",
        tornado.web.StaticFileHandler,
        {"path": os.path.join(os.path.dirname(__file__), "..", "static")},
    ),
    (
        r"/favicon.ico",
        tornado.web.StaticFileHandler,
        {
            "path": os.path.join(
                os.path.dirname(__file__), "..", "static", "favicon.ico"
            )
        },
    ),
    (r"/admin", admin_web_index.AdminRedirect),
    (r"/admin/", admin_web_index.AdminIndex),
    (r"/admin/album_list/associate_groups", admin_web_groups.AssociateGroupAlbumList),
    (r"/admin/album_list/cooldown", admin_web_cooldown.CooldownAlbumList),
    (
        r"/admin/album_list/disassociate_groups",
        admin_web_groups.DisassociateGroupAlbumList,
    ),
    (r"/admin/album_list/dj_election", admin_web_dj_election.DJElectionAlbumList),
    (r"/admin/album_list/donations", admin_web_donations.DonationAddTool),
    (r"/admin/album_list/group_edit", admin_web_groups.GroupEditGroupList),
    (r"/admin/album_list/js_errors", admin_web_js_errors.JSErrorDisplay),
    (r"/admin/album_list/modify_producer", admin_web_producers.WebModifyProducer),
    (r"/admin/album_list/power_hours", admin_web_power_hours.PowerHourAlbumList),
    (r"/admin/album_list/producers_all", admin_web_producers.WebListProducersAll),
    (r"/admin/album_list/producers", admin_web_producers.WebListProducers),
    (r"/admin/album_list/scan_results", admin_web_scan_errors.ScanResults),
    (
        r"/admin/album_list/song_request_only",
        admin_web_song_request_only.SongRequestOnlyAlbumList,
    ),
    (r"/admin/dj_election_list", admin_web_index.DJEventList),
    (r"/admin/dj_tools", admin_web_index.DJTools),
    (r"/admin/dj", admin_web_index.DJIndex),
    (r"/admin/relay_status", admin_web_index.RelayStatus),
    (r"/admin/restrict_songs", admin_web_index.RestrictList),
    (r"/admin/song_list/associate_groups", admin_web_groups.AssociateGroupSongList),
    (r"/admin/song_list/cooldown", admin_web_cooldown.CooldownSongList),
    (
        r"/admin/song_list/disassociate_groups",
        admin_web_groups.DisassociateGroupSongList,
    ),
    (r"/admin/song_list/dj_election", admin_web_dj_election.DJElectionSongList),
    (r"/admin/song_list/group_edit", admin_web_groups.GroupEditSongList),
    (r"/admin/song_list/power_hours", admin_web_power_hours.PowerHourSongList),
    (
        r"/admin/song_list/song_request_only",
        admin_web_song_request_only.SongRequestOnlyList,
    ),
    (r"/admin/station_list", admin_web_index.StationList),
    (r"/admin/tool_list", admin_web_index.ToolList),
    (
        r"/admin/tools/associate_groups_cache_reset",
        admin_web_groups.AssociateGroupCacheReset,
    ),
    (
        r"/admin/tools/associate_groups_finish/(\d+)",
        admin_web_groups.AssociateGroupToolFinish,
    ),
    (r"/admin/tools/associate_groups", admin_web_groups.AssociateGroupTool),
    (r"/admin/tools/cooldown", admin_web_cooldown.CooldownTool),
    (r"/admin/tools/disassociate_groups", admin_web_groups.DisassociateGroupTool),
    (r"/admin/tools/dj_election", admin_web_dj_election.DJElectionTool),
    (r"/admin/tools/donations", admin_web_donations.UserSearchTool),
    (r"/admin/tools/group_edit", admin_web_groups.GroupEditTool),
    (r"/admin/tools/js_errors", admin_web_js_errors.JSErrorsDummy),
    (r"/admin/tools/power_hour_detail", admin_web_power_hours.WebPowerHourDetail),
    (r"/admin/tools/power_hours", admin_web_power_hours.WebListPowerHours),
    (r"/admin/tools/producers_all", admin_web_producers.WebCreateProducerAll),
    (r"/admin/tools/producers", admin_web_producers.WebCreateProducer),
    (r"/admin/tools/scan_results", admin_web_scan_errors.LatestSongs),
    (
        r"/admin/tools/song_request_only",
        admin_web_song_request_only.SongRequestOnlyTool,
    ),
    (r"/api4/admin/add_album_to_power_hour", admin_power_hours.AddAlbumToPowerHour),
    (r"/api4/admin/add_donation", admin_donations.AddDonationHandler),
    (r"/api4/admin/add_song_to_power_hour", admin_power_hours.AddSongToPowerHour),
    (r"/api4/admin/add_to_dj_election", admin_dj_election.AddToDJElection),
    (
        r"/api4/admin/associate_groups_add_album",
        admin_web_groups.AssociateGroupAddAlbum,
    ),
    (r"/api4/admin/associate_groups_add_song", admin_web_groups.AssociateGroupAddSong),
    (r"/api4/admin/backend_scan_errors", admin_js_errors.JSErrors),
    (r"/api4/admin/backend_scan_errors", admin_scan_errors.BackendScanErrors),
    (r"/api4/admin/change_producer_end_time", admin_producers.ChangeProducerEndTime),
    (r"/api4/admin/change_producer_name", admin_producers.ChangeProducerName),
    (
        r"/api4/admin/change_producer_start_time",
        admin_producers.ChangeProducerStartTime,
    ),
    (r"/api4/admin/change_producer_url", admin_producers.ChangeProducerURL),
    (r"/api4/admin/commit_dj_election", admin_dj_election.CommitDJElection),
    (r"/api4/admin/create_group", admin_groups.CreateGroup),
    (r"/api4/admin/create_producer", admin_producers.CreateProducer),
    (r"/api4/admin/delete_election", admin_dj_election.DeleteElection),
    (r"/api4/admin/delete_producer", admin_producers.DeleteProducer),
    (r"/api4/admin/dj/change_pw", admin_dj.ChangeDJPW),
    (r"/api4/admin/dj/heartbeat", admin_dj.DJHeartbeat),
    (r"/api4/admin/dj/pause_title", admin_dj.PauseTitle),
    (r"/api4/admin/dj/pause", admin_dj.PauseStation),
    (r"/api4/admin/dj/skip", admin_dj.SkipStation),
    (r"/api4/admin/dj/unpause", admin_dj.UnpauseStation),
    (r"/api4/admin/duplicate_producer", admin_producers.DuplicateProducer),
    (r"/api4/admin/edit_group_cooldown", admin_groups.EditGroupCooldown),
    (r"/api4/admin/edit_group_elec_block", admin_groups.EditGroup),
    (r"/api4/admin/europify_producer", admin_producers.EuropifyProducer),
    (r"/api4/admin/get_dj_election", admin_dj_election.GetDJElection),
    (r"/api4/admin/get_power_hour", admin_power_hours.GetPowerHour),
    (r"/api4/admin/list_power_hours", admin_power_hours.ListPowerHours),
    (r"/api4/admin/list_producer_types", admin_producers.ListProducerTypes),
    (r"/api4/admin/list_producers_all", admin_producers.ListProducersAll),
    (r"/api4/admin/list_producers", admin_producers.ListProducers),
    (r"/api4/admin/move_up_in_power_hour", admin_power_hours.MoveUpInPowerHour),
    (r"/api4/admin/remove_from_dj_election", admin_dj_election.RemoveFromDJElection),
    (r"/api4/admin/remove_from_power_hour", admin_power_hours.RemoveFromPowerHour),
    (r"/api4/admin/remove_group_from_song", admin_groups.RemoveGroupFromSong),
    (r"/api4/admin/request_line", admin_request_line.ListRequestLine),
    (r"/api4/admin/reset_album_cooldown", admin_cooldown.ResetAlbumCooldown),
    (r"/api4/admin/reset_song_cooldown", admin_cooldown.ResetSongCooldown),
    (r"/api4/admin/set_album_cooldown", admin_cooldown.SetAlbumCooldown),
    (r"/api4/admin/set_song_cooldown", admin_cooldown.SetSongCooldown),
    (r"/api4/admin/set_song_request_only", admin_song_request_only.SetSongRequestOnly),
    (r"/api4/admin/shuffle_power_hour", admin_power_hours.ShufflePowerHour),
    (r"/api4/album", playlist.AlbumHandler),
    (r"/api4/all_albums_paginated", playlist.AllAlbumsPaginatedHandler),
    (r"/api4/all_albums", playlist.AllAlbumsHandler),
    (r"/api4/all_artists_paginated", playlist.AllArtistsPaginatedHandler),
    (r"/api4/all_artists", playlist.AllArtistsHandler),
    (r"/api4/all_faves", playlist.AllFavHandler),
    (r"/api4/all_groups_paginated", playlist.AllGroupsPaginatedHandler),
    (r"/api4/all_groups", playlist.AllGroupsHandler),
    (r"/api4/all_songs", playlist.AllSongsHandler),
    (r"/api4/artist", playlist.ArtistHandler),
    (r"/api4/bootstrap_dj", main.DJBootstrap),
    (r"/api4/bootstrap", main.Bootstrap),
    (r"/api4/clear_rating", rating.ClearRating),
    (r"/api4/clear_requests_on_cooldown", request.ClearRequestsOnCooldown),
    (r"/api4/clear_requests", request.ClearRequests),
    (r"/api4/current_listeners", listener.CurrentListenersRequest),
    (r"/api4/delete_request", request.DeleteRequest),
    (
        r"/api4/enable_perks_by_discord_ids",
        admin_enable_perks.UserSearchByDiscordUserIdRequest,
    ),
    (r"/api4/error_report", error.ErrorReport),
    (r"/api4/fave_album", fave.SubmitAlbumFave),
    (r"/api4/fave_all_songs", fave.SubmitFaveAllSongs),
    (r"/api4/fave_song", fave.SubmitSongFave),
    (r"/api4/group", playlist.GroupHandler),
    (r"/api4/info_all", info.InfoAllRequest),
    (r"/api4/info", info.InfoRequest),
    (r"/api4/listener_add/(\d+)", ldetect.AddListener),
    (r"/api4/listener_remove", ldetect.RemoveListener),
    (r"/api4/listener", listener.ListenerDetailRequest),
    (r"/api4/order_requests", request.OrderRequests),
    (r"/api4/pause_request_queue", request.PauseRequestQueue),
    (r"/api4/playback_history", playlist.PlaybackHistory),
    (r"/api4/power_hours", power_hours.ListPowerHours),
    (r"/api4/rate", rating.SubmitRatingRequest),
    (r"/api4/request_favorited_songs", request.RequestFavoritedSongs),
    (r"/api4/request_line", request.ListRequestLine),
    (r"/api4/request_unrated_songs", request.RequestUnratedSongs),
    (r"/api4/request", request.SubmitRequest),
    (r"/api4/search", search.SearchHandler),
    (r"/api4/song", playlist.SongHandler),
    (r"/api4/station_song_count", playlist.StationSongCountRequest),
    (r"/api4/stations", info.StationsRequest),
    (r"/api4/sync", sync.Sync),
    (r"/api4/test/create_anon_tuned_in/(\d+)", admin_web_developer.CreateAnonTunedIn),
    (r"/api4/test/login_tuned_in/(\d+)", admin_web_developer.CreateLoginTunedIn),
    (r"/api4/test/login_tuned_out/(\d+)", admin_web_developer.CreateLoginTunedOut),
    (r"/api4/tip_jar", tip_jar.TipJarContents),
    (r"/api4/top_100", playlist.Top100Songs),
    (r"/api4/unpause_request_queue", request.UnPauseRequestQueue),
    (r"/api4/unrated_songs", playlist.UnratedSongsHandler),
    (
        r"/api4/update_user_avatar_by_discord_id",
        admin_update_user_avatar.UpdateUserAvatarByDiscordId,
    ),
    (
        r"/api4/update_user_nickname_by_discord_id",
        admin_update_user_nickname.UpdateUserNicknameByDiscordId,
    ),
    (r"/api4/user_info", listener.UserInfoRequest),
    (r"/api4/user_recent_votes", playlist.RecentlyVotedSongs),
    (r"/api4/user_requested_history", playlist.AllRequestedSongs),
    (
        r"/api4/user_search_by_discord_user_id",
        admin_user_search.UserSearchByDiscordUserIdRequest,
    ),
    (r"/api4/user_search", admin_user_search.UserSearchRequest),
    (r"/api4/vote", vote.SubmitVote),
    (r"/api4/websocket/(\d+)", sync.WSHandler),
    (r"/blank", main.Blank),
    (r"/keys/", key_management.KeyIndex),
    (r"/keys/app", key_management.AppLogin),
    (r"/keys/create", key_management.KeyCreate),
    (r"/keys/delete", key_management.KeyDelete),
    (r"/locale/", locale.LocaleIndex),
    (r"/locale/(\w+)", locale.LocaleMissingLines),
    (r"/manifest.json", manifest.ManifestJSON),
    (r"/oauth/debug", auth_debug.DebugAuth),
    (r"/oauth/discord", auth_discord.DiscordAuth),
    (r"/oauth/login", auth_login.PhpbbAuth),
    (r"/oauth/logout", auth_logout.Logout),
    (r"/oauth/tos_privacy", auth_tos_privacy.RainwaveTOSPrivacy),
    (r"/pages/all_faves", playlist.AllFavHTML),
    (r"/pages/current_listeners", listener.CurrentListenersHTML),
    (r"/pages/playback_history", playlist.PlaybackHistoryHTML),
    (r"/pages/power_hours", power_hours.AllRequestedSongsHTML),
    (r"/pages/request_line", admin_request_line.ListRequestLineHTML),
    (r"/pages/request_line", request.ListRequestLineHTML),
    (r"/pages/tip_jar", tip_jar.TipJarHTML),
    (r"/pages/top_100", playlist.Top100SongsHTML),
    (r"/pages/unrated_songs", playlist.UnratedSongsHTML),
    (r"/pages/user_recent_votes", playlist.RecentlyVotedSongsHTML),
    (r"/pages/user_requested_history", playlist.AllRequestedSongsHTML),
    (r"/sync/(\d+)/listener_add", ldetect.AddListener_R3Relay),
    (r"/sync/(\d+)/listener_remove", ldetect.RemoveListener_R3Relay),
    (r"/tune_in/(\w+|\d)\.(ogg|mp3)(.m3u)?", tune_in.TuneInIndex),
    (r"/twitch/?", streamer.StreamHelp),
    (r"/twitch/widget", streamer.StreamIndex),
    (r"/widget/?", streamer.StreamHelp),
    (r"/widget/widget", streamer.StreamIndex),
]

__all__ = ["request_classes"]
