<?php
// many thanks to http://techpatterns.com/downloads/php_language_detection.php
function getDefaultLanguage() {
	$lang = array(
		// 'af' => 'Afrikaans',
		// 'sq' => 'Albanian',
		// 'ar-dz' => 'Arabic (Algeria)',
		// 'ar-bh' => 'Arabic (Bahrain)',
		// 'ar-eg' => 'Arabic (Egypt)',
		// 'ar-iq' => 'Arabic (Iraq)',
		// 'ar-jo' => 'Arabic (Jordan)',
		// 'ar-kw' => 'Arabic (Kuwait)',
		// 'ar-lb' => 'Arabic (Lebanon)',
		// 'ar-ly' => 'Arabic (libya)',
		// 'ar-ma' => 'Arabic (Morocco)',
		// 'ar-om' => 'Arabic (Oman)',
		// 'ar-qa' => 'Arabic (Qatar)',
		// 'ar-sa' => 'Arabic (Saudi Arabia)',
		// 'ar-sy' => 'Arabic (Syria)',
		// 'ar-tn' => 'Arabic (Tunisia)',
		// 'ar-ae' => 'Arabic (U.A.E.)',
		// 'ar-ye' => 'Arabic (Yemen)',
		// 'ar' => 'Arabic',
		// 'hy' => 'Armenian',
		// 'as' => 'Assamese',
		// 'az' => 'Azeri',
		// 'eu' => 'Basque',
		// 'be' => 'Belarusian',
		// 'bn' => 'Bengali',
		// 'bg' => 'Bulgarian',
		// 'ca' => 'Catalan',
		// 'zh-cn' => 'Chinese (China)',
		// 'zh-hk' => 'Chinese (Hong Kong SAR)',
		// 'zh-mo' => 'Chinese (Macau SAR)',
		// 'zh-sg' => 'Chinese (Singapore)',
		// 'zh-tw' => 'Chinese (Taiwan)',
		// 'zh' => 'Chinese',
		// 'hr' => 'Croatian',
		// 'cs' => 'Czech',
		// 'da' => 'Danish',
		// 'div' => 'Divehi',
		'nl-be' => 'nl_NL', //'Dutch (Belgium)',
		'nl' => 'nl_NL', //'Dutch (Netherlands)',
		// 'et' => 'Estonian',
		// 'fo' => 'Faeroese',
		// 'fa' => 'Farsi',
		'fi' => 'fi_FI', //'Finnish',
		'fr-be' => 'fr_CA', //'French (Belgium)',
		'fr-ca' => 'fr_CA', //'French (Canada)',
		'fr-lu' => 'fr_CA', //'French (Luxembourg)',
		'fr-mc' => 'fr_CA', //'French (Monaco)',
		'fr-ch' => 'fr_CA', //'French (Switzerland)',
		'fr' => 'fr_CA', //'French (France)',
		// 'mk' => 'FYRO Macedonian',
		// 'gd' => 'Gaelic',
		// 'ka' => 'Georgian',
		'de-at' => 'de_DE', //'German (Austria)',
		'de-li' => 'de_DE', //'German (Liechtenstein)',
		'de-lu' => 'de_DE', //'German (Luxembourg)',
		'de-ch' => 'de_DE', //'German (Switzerland)',
		'de' => 'de_DE', //'German (Germany)',
		// 'el' => 'Greek',
		// 'gu' => 'Gujarati',
		// 'he' => 'Hebrew',
		// 'hi' => 'Hindi',
		// 'hu' => 'Hungarian',
		// 'is' => 'Icelandic',
		// 'id' => 'Indonesian',
		// 'it-ch' => 'Italian (Switzerland)',
		// 'it' => 'Italian (Italy)',
		// 'ja' => 'Japanese',
		// 'kn' => 'Kannada',
		// 'kk' => 'Kazakh',
		// 'kok' => 'Konkani',
		// 'ko' => 'Korean',
		// 'kz' => 'Kyrgyz',
		// 'lv' => 'Latvian',
		// 'lt' => 'Lithuanian',
		// 'ms' => 'Malay',
		// 'ml' => 'Malayalam',
		// 'mt' => 'Maltese',
		// 'mr' => 'Marathi',
		// 'mn' => 'Mongolian (Cyrillic)',
		// 'ne' => 'Nepali (India)',
		// 'nb-no' => 'Norwegian (Bokmal)',
		// 'nn-no' => 'Norwegian (Nynorsk)',
		// 'no' => 'Norwegian (Bokmal)',
		// 'or' => 'Oriya',
		// 'pl' => 'Polish',
		'pt-br' => 'pt_BR', //'Portuguese (Brazil)',
		'pt' => 'pt_BR', //'Portuguese (Portugal)',
		// 'pa' => 'Punjabi',
		// 'rm' => 'Rhaeto-Romanic',
		// 'ro-md' => 'Romanian (Moldova)',
		// 'ro' => 'Romanian',
		// 'ru-md' => 'Russian (Moldova)',
		// 'ru' => 'Russian',
		// 'sa' => 'Sanskrit',
		// 'sr' => 'Serbian',
		// 'sk' => 'Slovak',
		// 'ls' => 'Slovenian',
		// 'sb' => 'Sorbian',
		'es-ar' => 'es_CL', //'Spanish (Argentina)',
		'es-bo' => 'es_CL', //'Spanish (Bolivia)',
		'es-cl' => 'es_CL', //'Spanish (Chile)',
		'es-co' => 'es_CL', //'Spanish (Colombia)',
		'es-cr' => 'es_CL', //'Spanish (Costa Rica)',
		'es-do' => 'es_CL', //'Spanish (Dominican Republic)',
		'es-ec' => 'es_CL', //'Spanish (Ecuador)',
		'es-sv' => 'es_CL', //'Spanish (El Salvador)',
		'es-gt' => 'es_CL', //'Spanish (Guatemala)',
		'es-hn' => 'es_CL', //'Spanish (Honduras)',
		'es-mx' => 'es_CL', //'Spanish (Mexico)',
		'es-ni' => 'es_CL', //'Spanish (Nicaragua)',
		'es-pa' => 'es_CL', //'Spanish (Panama)',
		'es-py' => 'es_CL', //'Spanish (Paraguay)',
		'es-pe' => 'es_CL', //'Spanish (Peru)',
		'es-pr' => 'es_CL', //'Spanish (Puerto Rico)',
		'es-us' => 'es_CL', //'Spanish (United States)',
		'es-uy' => 'es_CL', //'Spanish (Uruguay)',
		'es-ve' => 'es_CL', //'Spanish (Venezuela)',
		//'es' => 'es_CL', //'Spanish (Traditional Sort)',
		// 'sx' => 'Sutu',
		// 'sw' => 'Swahili',
		//'sv-fi' => 'Swedish (Finland)',
		'sv' => 'se_SE', //'Swedish',
		// 'syr' => 'Syriac',
		// 'ta' => 'Tamil',
		// 'tt' => 'Tatar',
		// 'te' => 'Telugu',
		// 'th' => 'Thai',
		// 'ts' => 'Tsonga',
		// 'tn' => 'Tswana',
		// 'tr' => 'Turkish',
		// 'uk' => 'Ukrainian',
		// 'ur' => 'Urdu',
		// 'uz' => 'Uzbek',
		// 'vi' => 'Vietnamese',
		// 'xh' => 'Xhosa',
		// 'yi' => 'Yiddish',
		// 'zu' => 'Zulu'
	);
	
	if (isset($_SERVER["HTTP_ACCEPT_LANGUAGE"])) {
		// example: ' fr-ch;q=0.3, da, en-us;q=0.8, en;q=0.5, fr;q=0.3';
		$languages = strtolower($_SERVER["HTTP_ACCEPT_LANGUAGE"]);
		$languages = str_replace(' ', '', $languages);
		$languages = explode(",", $languages);
		for ($i = 0; $i < count($languages); $i++ ) {
			$bits = explode(";", $languages[$i]);
			if (isset($lang[$bits[0]])) {
				return $lang[$bits[0]];
			}
		}
	}
	return "en_CA";
}
?>