from typing import Any, Self

class PostgresContainer:
    def __init__(self, image: str, **kwargs: Any) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any
    ) -> None: ...
    def get_connection_url(self) -> str: ...
