from typing import Any, Self

class PostgresContainer:
    def __init__(self, image: str, **kwargs: Any) -> None: ...
    def start(self) -> Self: ...
    def stop(self, force: bool = True, delete_volume: bool = True) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any
    ) -> None: ...
    def get_connection_url(self) -> str: ...
    def get_container_host_ip(self) -> str: ...
    def get_exposed_port(self, port: int) -> int: ...
