import type {
  AlbumDiff,
  AllAlbumsPaginated,
  AllArtistsPaginated,
  AllGroupsPaginated,
} from './types';
import type { AlbumWithDetail } from './types/albumWithDetail';
import type { AllSongsSong } from './types/allSongsSong';
import type { AllStationsInfo } from './types/allStationsInfo';
import type { AlreadyVoted } from './types/alreadyVoted';
import type { ApiInfo } from './types/apiInfo';
import type { ArtistWithSongs } from './types/artistWithSongs';
import type { BooleanResult } from './types/booleanResult';
import type { FaveAlbumResult } from './types/faveAlbumResult';
import type { FaveAllSongsResult } from './types/faveAllSongsResult';
import type { FaveSong } from './types/faveSong';
import type { FaveSongResult } from './types/faveSongResult';
import type { GroupWithDetail } from './types/groupWithDetail';
import type { Listener } from './types/listener';
import type { LiveVoting } from './types/liveVoting';
import type { MessageId } from './types/messageId';
import type { Ping } from './types/ping';
import type { PlaybackHistory } from './types/playbackHistory';
import type { Pong } from './types/pong';
import type { PongConfirm } from './types/pongConfirm';
import type { RainwaveErrorObject } from './types/rainwaveErrorObject';
import type { RainwaveEvent } from './types/rainwaveEvent';
import type { RateResult } from './types/rateResult';
import type { RedownloadM3u } from './types/redownloadM3u';
import type { Relays } from './types/relays';
import type { RequestLine } from './types/requestLine';
import type { Requests } from './types/requests';
import type { RainwaveSDKErrorClear } from './types/sdkErrorClear';
import type { SearchResult } from './types/searchResults';
import type { SongWithDetail } from './types/songWithDetail';
import type { Station } from './types/station';
import type { StationSongCount } from './types/stationSongCount';
import type { Stations } from './types/stations';
import type { Top100 } from './types/top100';
import type { UnratedSongs } from './types/unratedSongs';
import type { User } from './types/user';
import type { UserRecentVotes } from './types/userRecentVotes';
import type { VoteResult } from './types/voteResult';

export interface RainwaveResponseTypes {
  album: AlbumWithDetail;
  album_diff: AlbumDiff;
  albums: SearchResult['albums'];
  all_albums_paginated: AllAlbumsPaginated;
  all_artists_paginated: AllArtistsPaginated;
  all_faves: FaveSong[];
  all_groups_paginated: AllGroupsPaginated;
  all_songs: AllSongsSong[];
  all_stations_info: AllStationsInfo;
  already_voted: AlreadyVoted;
  api_info: ApiInfo;
  artists: SearchResult['artists'];
  artist: ArtistWithSongs;
  build_version: number;
  cookie_domain: string;
  delete_request_result: BooleanResult;
  error_report_result: BooleanResult;
  error: RainwaveErrorObject;
  fave_album_result: FaveAlbumResult;
  fave_all_songs_result: FaveAllSongsResult;
  fave_song_result: FaveSongResult;
  group: GroupWithDetail;
  listener: Listener;
  live_voting: LiveVoting;
  locale: string;
  locales: Record<string, string>;
  message_id: MessageId;
  mobile: boolean;
  on_draw: unknown[];
  on_init: unknown[];
  on_measure: unknown[];
  order_requests_result: BooleanResult;
  pause_request_queue_result: BooleanResult;
  ping: Ping;
  pong: Pong;
  pongConfirm: PongConfirm;
  playback_history: PlaybackHistory;
  rate_result: RateResult;
  redownload_m3u: RedownloadM3u;
  relays: Relays;
  request_favorited_songs_result: BooleanResult;
  request_line: RequestLine;
  request_result: BooleanResult;
  request_unrated_songs_result: BooleanResult;
  requests: Requests;
  sched_current: RainwaveEvent;
  sched_history: RainwaveEvent[];
  sched_next: RainwaveEvent[];
  sdk_exception: Error;
  sdk_error_clear: RainwaveSDKErrorClear;
  sdk_schedule_synced: true;
  song: SongWithDetail;
  songs: SearchResult['songs'];
  station_list: Record<Station, { id: number; url: string }>;
  station_song_count: StationSongCount;
  stations: Stations;
  stream_filename: string;
  sync_result: RainwaveErrorObject;
  top_100: Top100;
  unpause_request_queue_result: BooleanResult;
  unrated_songs: UnratedSongs;
  user_info: User;
  user_recent_votes: UserRecentVotes;
  user_requested_history: UserRecentVotes;
  user: User;
  vote_result: VoteResult;
  websocket_host: string;
  wsok: true;
  wsthrottle: { tl_key: string; text: string };
  wserror: RainwaveErrorObject;
}

export interface RainwaveBootstrap {
  all_stations_info: RainwaveResponseTypes['all_stations_info'];
  already_voted: RainwaveResponseTypes['already_voted'];
  api_info: RainwaveResponseTypes['api_info'];
  build_version: RainwaveResponseTypes['build_version'];
  cookie_domain: RainwaveResponseTypes['cookie_domain'];
  live_voting: RainwaveResponseTypes['live_voting'];
  locale: RainwaveResponseTypes['locale'];
  locales: RainwaveResponseTypes['locales'];
  mobile: boolean;
  on_draw: Array<() => void>;
  on_init: Array<() => void>;
  on_measure: Array<() => void>;
  relays: RainwaveResponseTypes['relays'];
  request_line: RainwaveResponseTypes['request_line'];
  requests: RainwaveResponseTypes['requests'];
  sched_current: RainwaveResponseTypes['sched_current'];
  sched_history: RainwaveResponseTypes['sched_history'];
  sched_next: RainwaveResponseTypes['sched_next'];
  station_list: RainwaveResponseTypes['station_list'];
  stream_filename: RainwaveResponseTypes['stream_filename'];
  user: User & { api_key: string };
  websocket_host: RainwaveResponseTypes['websocket_host'];
}
