# generated by datamodel-codegen:
#   filename:  rainwave-openapi.json
#   timestamp: 2026-02-23T16:16:30+00:00

from enum import Enum, StrEnum
from pydantic import BaseModel, Field, RootModel
from typing import Any


class Sort(StrEnum):
    added_on = "added_on"
    name = "name"  # type: ignore


class Api4AlbumPostRequest(BaseModel):
    id: int
    sort: Sort | None = Field(
        None, description="How to sort the songs that are a part of the album."
    )
    user_id: int
    api_key: str
    sid: int


class Api4AllAlbumsPaginatedPostRequest(BaseModel):
    after: int | None = None
    user_id: int
    api_key: str
    sid: int


class Api4AllArtistsPaginatedPostRequest(BaseModel):
    after: int | None = None
    user_id: int
    api_key: str
    sid: int


class Api4AllFavesPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    user_id: int
    api_key: str


class Api4AllGroupsPaginatedPostRequest(BaseModel):
    after: int | None = None
    user_id: int
    api_key: str
    sid: int


class Order(StrEnum):
    rating = "rating"


class Api4AllSongsPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    order: Order | None = None
    user_id: int
    api_key: str


class Api4ArtistPostRequest(BaseModel):
    id: int
    user_id: int
    api_key: str
    sid: int


class Api4ClearRatingPostRequest(BaseModel):
    song_id: int
    user_id: int
    api_key: str
    sid: int


class Api4ClearRequestsPostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4ClearRequestsOnCooldownPostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4DeleteRequestPostRequest(BaseModel):
    song_id: int
    user_id: int
    api_key: str
    sid: int


class Api4FaveAlbumPostRequest(BaseModel):
    album_id: int
    fave: bool
    user_id: int
    api_key: str
    sid: int


class Api4FaveAllSongsPostRequest(BaseModel):
    album_id: int
    fave: bool
    user_id: int
    api_key: str
    sid: int


class Api4FaveSongPostRequest(BaseModel):
    song_id: int
    fave: bool
    user_id: int
    api_key: str


class Api4GroupPostRequest(BaseModel):
    id: int
    user_id: int
    api_key: str
    sid: int


class Api4InfoAllPostRequest(BaseModel):
    sid: int


class Api4ListenerPostRequest(BaseModel):
    id: int
    user_id: int
    api_key: str


class Api4OrderRequestsPostRequest(BaseModel):
    order: str = Field(
        ...,
        description="A comma-separated list of Song IDs that represent the user's request queue, in the order the user desires.",
    )
    user_id: int
    api_key: str
    sid: int


class Api4PauseRequestQueuePostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4PlaybackHistoryPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    user_id: int
    api_key: str
    sid: int


class Rating(Enum):
    number_1 = 1
    number_1_5 = 1.5
    number_2 = 2
    number_2_5 = 2.5
    number_3 = 3
    number_3_5 = 3.5
    number_4 = 4
    number_4_5 = 4.5
    number_5 = 5


class Api4RatePostRequest(BaseModel):
    song_id: int
    rating: Rating
    user_id: int
    api_key: str
    sid: int


class Api4RequestPostRequest(BaseModel):
    song_id: int
    user_id: int
    api_key: str
    sid: int


class Api4RequestFavoritedSongsPostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4RequestLinePostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4RequestUnratedSongsPostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4SearchPostRequest(BaseModel):
    search: str
    user_id: int
    api_key: str
    sid: int


class Api4SongPostRequest(BaseModel):
    id: int
    user_id: int
    api_key: str
    sid: int


class Api4StationSongCountPostRequest(BaseModel):
    user_id: int
    api_key: str


class Api4UnpauseRequestQueuePostRequest(BaseModel):
    user_id: int
    api_key: str
    sid: int


class Api4UnratedSongsPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    user_id: int
    api_key: str
    sid: int


class Api4UserInfoPostRequest(BaseModel):
    user_id: int
    api_key: str


class Api4UserRecentVotesPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    user_id: int
    api_key: str
    sid: int


class Api4UserRequestedHistoryPostRequest(BaseModel):
    per_page: int | None = None
    page_start: int | None = None
    user_id: int
    api_key: str
    sid: int


class Api4VotePostRequest(BaseModel):
    entry_id: int
    user_id: int
    api_key: str
    sid: int


class AllStationsInfo(BaseModel):
    pass


class Artist(BaseModel):
    id: int
    name: str


class FaveAlbumResult(BaseModel):
    id: int
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class FaveAllSongsResult(BaseModel):
    song_ids: list[int]
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class FaveSongResult(BaseModel):
    id: int
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class User(BaseModel):
    admin: bool
    avatar: str | None = None
    id: int
    listen_key: str | None
    listener_id: int | None
    lock_counter: int
    lock_in_effect: bool
    lock_sid: int | None
    lock: bool
    name: str
    new_privmsg: int
    perks: bool
    rate_anything: bool
    request_expires_at: int | None
    request_position: int | None
    requests_paused: bool
    sid: int
    tuned_in: bool
    voted_entry: int | None


class VoteResult(BaseModel):
    elec_id: int
    entry_id: int
    success: bool
    tl_key: str
    text: str


class AlbumInList(BaseModel):
    id: int
    name: str
    rating: float | None
    cool: bool
    cool_lowest: int
    fave: bool | None
    rating_user: float | None
    rating_complete: bool | None
    newest_song_time: int


class AllSongsSong(BaseModel):
    album_name: str
    fave: bool | None
    id: int
    rating: int | None
    rating_user: int | None
    title: str


class ArtistInList(BaseModel):
    id: int
    name: str
    song_count: int


class BooleanResult(BaseModel):
    success: bool
    tl_key: str
    text: str


class FaveSong(BaseModel):
    album_id: int
    album_name: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    title: str


class GroupInList(BaseModel):
    id: int
    name: str


class GroupWithDetail(BaseModel):
    id: int
    name: str
    all_songs_for_sid: dict[str, Any]


class ListenerRatingSpreadItem(BaseModel):
    ratings: int
    rating: int


class ListenerRatingsByStation(BaseModel):
    sid: int
    average_rating: str
    ratings: int


class ListenerRequestsByStation(BaseModel):
    sid: int
    requests: int


class ListenerTopAlbum(BaseModel):
    id: int
    name: str
    rating_listener: int
    rating: int


class ListenerTopRequestAlbum(BaseModel):
    id: int
    name: str
    request_count_listener: int


class ListenerVotesByStation(BaseModel):
    sid: int
    votes: int


class PlaybackHistoryEntry(BaseModel):
    album_id: int
    album_name: str
    artist_parseable: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    song_played_at: int
    title: str


class RainwaveErrorObject(BaseModel):
    status: int
    tl_key: str
    text: str | None = None
    success: bool | None = None


class RequestLineEntry(BaseModel):
    username: str
    user_id: int
    line_expiry_tune_in: int | None
    line_expiry_election: int | None
    line_wait_start: int
    line_has_had_valid: bool
    song_id: int | None
    skip: bool
    position: int


class SearchAlbum(BaseModel):
    id: int
    name: str
    cool: bool
    rating: int | None
    fave: bool | None
    rating_user: int | None
    rating_complete: bool | None


class SearchArtist(BaseModel):
    id: int
    name: str


class SearchSong(BaseModel):
    added_on: int
    album_id: int
    album_name: str
    cool_end: int
    cool: bool
    origin_sid: int
    requestable: bool
    id: int
    rating: int
    fave: bool | None
    rating_user: int | None
    title: str
    length: int
    link_text: str | None
    url: str | None


class AlbumItem(BaseModel):
    id: int
    name: str
    rating: int | None
    fave: bool | None
    rating_user: int | None
    art: str | None
    rating_complete: bool | None


class Album1(BaseModel):
    id: int
    name: str


class StationSongCountByStation(BaseModel):
    sid: int
    song_count: int


class UnratedSong(BaseModel):
    album_name: str
    id: int
    title: str


class UpdatedAlbumRating(BaseModel):
    sid: int
    id: int
    rating_user: int | None
    rating_complete: bool | None


class UserRecentVote(BaseModel):
    album_name: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    title: str


class RequestAlbum(BaseModel):
    name: str
    id: int
    rating: int | None
    rating_user: int | None
    rating_complete: bool | None
    art: str | None


class SongGroup(BaseModel):
    id: int
    name: str


class SongOnAlbum(BaseModel):
    origin_sid: int
    added_on: int
    cool_multiply: int | None = None
    cool_override: int | None = None
    requestable: bool
    cool: bool
    cool_end: int
    request_only_end: int
    request_only: bool
    albums: tuple[Album1]
    artists: list[Artist]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


class SongWithDetailArtist(BaseModel):
    order: int
    id: int
    name: str


class Top100Song(BaseModel):
    album_name: str
    id: int
    origin_sid: int
    song_rating: int
    song_rating_count: int
    title: str


class Relay(BaseModel):
    name: str
    protocol: str
    hostname: str
    port: int


class Api4ArtistPostResponse(BaseModel):
    artist: Artist


class Api4FaveAlbumPostResponse(BaseModel):
    fave_album_result: FaveAlbumResult


class Api4FaveAllSongsPostResponse(BaseModel):
    fave_all_songs_result: FaveAllSongsResult


class Api4FaveSongPostResponse(BaseModel):
    fave_song_result: FaveSongResult


class Api4InfoAllPostResponse(BaseModel):
    all_stations_info: AllStationsInfo


class Api4UserInfoPostResponse(BaseModel):
    user_info: User


class Api4VotePostResponse(BaseModel):
    vote: VoteResult


class Albums(RootModel[list[SearchAlbum]]):
    root: list[SearchAlbum]


class AllAlbumsPaginated(BaseModel):
    data: list[AlbumInList]
    has_next: bool
    next: int
    progress: int


class AllArtistsPaginated(BaseModel):
    data: list[ArtistInList]
    has_next: bool
    next: int
    progress: int


class AllFaves(RootModel[list[FaveSong]]):
    root: list[FaveSong]


class AllGroupsPaginated(BaseModel):
    data: list[GroupInList]
    has_next: bool
    next: int
    progress: int


class AllSongs(RootModel[list[AllSongsSong]]):
    root: list[AllSongsSong]


class Artists(RootModel[list[SearchArtist]]):
    root: list[SearchArtist]


class Error(RootModel[RainwaveErrorObject]):
    root: RainwaveErrorObject


class Group(RootModel[GroupWithDetail]):
    root: GroupWithDetail


class Listener(BaseModel):
    user_id: int
    name: str
    avatar: str | None
    colour: str
    rank: str
    total_votes: int
    total_ratings: int
    mind_changes: int
    total_requests: int
    winning_votes: int
    losing_votes: int
    regdate: int
    top_albums: list[ListenerTopAlbum]
    top_request_albums: list[ListenerTopRequestAlbum]
    votes_by_station: list[ListenerVotesByStation]
    requests_by_station: list[ListenerRequestsByStation]
    requests_by_source_station: list[ListenerRequestsByStation]
    ratings_by_station: list[ListenerRatingsByStation]
    ratings_completion: dict[str, Any]
    rating_spread: list[ListenerRatingSpreadItem]


class OrderRequestsResult(RootModel[BooleanResult]):
    root: BooleanResult


class PauseRequestQueueResult(RootModel[BooleanResult]):
    root: BooleanResult


class PlaybackHistory(RootModel[list[PlaybackHistoryEntry]]):
    root: list[PlaybackHistoryEntry]


class RateResult(BaseModel):
    updated_album_ratings: list[UpdatedAlbumRating]
    song_id: int
    rating_user: int | None
    success: bool
    tl_key: str
    text: str


class RequestFavoritedSongsResult(RootModel[BooleanResult]):
    root: BooleanResult


class RequestLine(RootModel[list[RequestLineEntry]]):
    root: list[RequestLineEntry]


class RequestUnratedSongsResult(RootModel[BooleanResult]):
    root: BooleanResult


class Songs(RootModel[list[SearchSong]]):
    root: list[SearchSong]


class StationSongCount(RootModel[list[StationSongCountByStation]]):
    root: list[StationSongCountByStation]


class UnpauseRequestQueueResult(RootModel[BooleanResult]):
    root: BooleanResult


class UnratedSongs(RootModel[list[UnratedSong]]):
    root: list[UnratedSong]


class UserRecentVotes(RootModel[list[UserRecentVote]]):
    root: list[UserRecentVote]


class UserRequestedHistory(RootModel[UserRecentVotes]):
    root: UserRecentVotes


class AlbumWithDetail(BaseModel):
    genres: list[SongGroup]
    rating_complete: bool | None
    rating_rank: int
    rating_rank_percentile: int
    request_count: int
    request_rank: int
    request_rank_percentile: int
    rating_histogram: dict[str, Any]
    songs: list[SongOnAlbum]
    added_on: int
    art: str | None
    cool_lowest: int
    cool_multiply: int | None = None
    cool_override: int | None = None
    cool: bool
    fave_count: int
    fave: bool | None
    id: int
    name: str
    played_last: int
    rating_count: int
    rating_user: int | None
    rating: int | None
    song_count: int
    vote_count: int


class Request(BaseModel):
    albums: tuple[RequestAlbum]
    cool_end: int
    cool: bool
    elec_blocked_by: str | None
    elec_blocked_num: int | None
    elec_blocked: bool
    good: bool
    order: int
    origin_sid: int
    request_id: int
    sid: int
    valid: bool
    artists: list[Artist]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


class SongWithDetail(BaseModel):
    album: tuple[AlbumItem]
    artists: list[SongWithDetailArtist]
    cool: bool
    elec_blocked_by: str | None
    elec_blocked: bool
    groups: list[SongGroup]
    origin_sid: int
    rating_allowed: bool
    rating_count: int
    rating_rank_percentile: int
    rating_rank: int
    request_count: int
    request_rank_percentile: int
    request_rank: int
    sid: int
    albums: tuple[Album1]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


class Top100(RootModel[list[Top100Song]]):
    root: list[Top100Song]


class Relays(RootModel[list[Relay]]):
    root: list[Relay]


class Api4WebsocketSidGetResponse(BaseModel):
    error: Error


class Api4AlbumPostResponse1(BaseModel):
    error: Error


class Api4AllAlbumsPaginatedPostResponse(BaseModel):
    all_albums_paginated: AllAlbumsPaginated


class Api4AllAlbumsPaginatedPostResponse1(BaseModel):
    error: Error


class Api4AllArtistsPaginatedPostResponse(BaseModel):
    all_artists_paginated: AllArtistsPaginated


class Api4AllArtistsPaginatedPostResponse1(BaseModel):
    error: Error


class Api4AllFavesPostResponse(BaseModel):
    all_faves: AllFaves


class Api4AllFavesPostResponse1(BaseModel):
    error: Error


class Api4AllGroupsPaginatedPostResponse(BaseModel):
    all_groups_paginated: AllGroupsPaginated


class Api4AllGroupsPaginatedPostResponse1(BaseModel):
    error: Error


class Api4AllSongsPostResponse(BaseModel):
    all_songs: AllSongs


class Api4AllSongsPostResponse1(BaseModel):
    error: Error


class Api4ArtistPostResponse1(BaseModel):
    error: Error


class Api4ClearRatingPostResponse(BaseModel):
    rate_result: RateResult


class Api4ClearRatingPostResponse1(BaseModel):
    error: Error


class Api4ClearRequestsPostResponse1(BaseModel):
    error: Error


class Api4ClearRequestsOnCooldownPostResponse1(BaseModel):
    error: Error


class Api4DeleteRequestPostResponse1(BaseModel):
    error: Error


class Api4FaveAlbumPostResponse1(BaseModel):
    error: Error


class Api4FaveAllSongsPostResponse1(BaseModel):
    error: Error


class Api4FaveSongPostResponse1(BaseModel):
    error: Error


class Api4GroupPostResponse(BaseModel):
    group: Group


class Api4GroupPostResponse1(BaseModel):
    error: Error


class Api4InfoAllPostResponse1(BaseModel):
    error: Error


class Api4ListenerPostResponse(BaseModel):
    listener: Listener


class Api4ListenerPostResponse1(BaseModel):
    error: Error


class Api4OrderRequestsPostResponse1(BaseModel):
    error: Error


class Api4PauseRequestQueuePostResponse(BaseModel):
    pause_request_queue_result: PauseRequestQueueResult
    user: User


class Api4PauseRequestQueuePostResponse1(BaseModel):
    error: Error


class Api4PlaybackHistoryPostResponse(BaseModel):
    playback_history: PlaybackHistory


class Api4PlaybackHistoryPostResponse1(BaseModel):
    error: Error


class Api4RatePostResponse(BaseModel):
    rate_result: RateResult


class Api4RatePostResponse1(BaseModel):
    error: Error


class Api4RequestPostResponse1(BaseModel):
    error: Error


class Api4RequestFavoritedSongsPostResponse1(BaseModel):
    error: Error


class Api4RequestLinePostResponse(BaseModel):
    request_line_result: RequestLine


class Api4RequestLinePostResponse1(BaseModel):
    error: Error


class Api4RequestUnratedSongsPostResponse1(BaseModel):
    error: Error


class Api4SearchPostResponse(BaseModel):
    albums: Albums
    artists: Artists
    songs: Songs


class Api4SearchPostResponse1(BaseModel):
    error: Error


class Api4SongPostResponse1(BaseModel):
    error: Error


class Api4StationSongCountPostResponse(BaseModel):
    station_song_count: StationSongCount


class Api4StationSongCountPostResponse1(BaseModel):
    error: Error


class Api4StationsPostResponse1(BaseModel):
    error: Error


class Api4Top100PostResponse1(BaseModel):
    error: Error


class Api4UnpauseRequestQueuePostResponse(BaseModel):
    unpause_request_queue_result: UnpauseRequestQueueResult
    user: User


class Api4UnpauseRequestQueuePostResponse1(BaseModel):
    error: Error


class Api4UnratedSongsPostResponse(BaseModel):
    unrated_songs: UnratedSongs


class Api4UnratedSongsPostResponse1(BaseModel):
    error: Error


class Api4UserInfoPostResponse1(BaseModel):
    error: Error


class Api4UserRecentVotesPostResponse(BaseModel):
    user_recent_votes: UserRecentVotes


class Api4UserRecentVotesPostResponse1(BaseModel):
    error: Error


class Api4UserRequestedHistoryPostResponse(BaseModel):
    user_requested_history: UserRequestedHistory


class Api4UserRequestedHistoryPostResponse1(BaseModel):
    error: Error


class Api4VotePostResponse1(BaseModel):
    error: Error


class Album(RootModel[AlbumWithDetail]):
    root: AlbumWithDetail


class Requests(RootModel[list[Request]]):
    root: list[Request]


class Song(RootModel[SongWithDetail]):
    root: SongWithDetail


class StationDescription(BaseModel):
    description: str
    id: int
    name: str
    relays: Relays
    stream: str


class Api4AlbumPostResponse(BaseModel):
    album: Album


class Api4ClearRequestsPostResponse(BaseModel):
    requests: Requests


class Api4ClearRequestsOnCooldownPostResponse(BaseModel):
    requests: Requests


class Api4DeleteRequestPostResponse(BaseModel):
    requests: Requests


class Api4OrderRequestsPostResponse(BaseModel):
    order_requests_result: OrderRequestsResult
    requests: Requests


class Api4RequestPostResponse(BaseModel):
    requests: Requests


class Api4RequestFavoritedSongsPostResponse(BaseModel):
    request_favorited_songs_result: RequestFavoritedSongsResult
    requests: Requests


class Api4RequestUnratedSongsPostResponse(BaseModel):
    request_unrated_songs_result: RequestUnratedSongsResult
    requests: Requests


class Api4SongPostResponse(BaseModel):
    song: Song


class Api4Top100PostResponse(BaseModel):
    top_100: Top100


class Stations(RootModel[list[StationDescription]]):
    root: list[StationDescription]


class Api4StationsPostResponse(BaseModel):
    stations: Stations
