# generated by datamodel-codegen:
#   filename:  rainwave-openapi.json
#   timestamp: 2026-02-23T16:16:31+00:00

from typing import Any, Literal, NotRequired, TypedDict


class AlbumDiffItem(TypedDict):
    id: int
    cool: bool
    cool_lowest: int
    newest_song_time: int


type AlbumDiff = list[AlbumDiffItem]


class AlbumInList(TypedDict):
    id: int
    name: str
    rating: float | None
    cool: bool
    cool_lowest: int
    fave: bool | None
    rating_user: float | None
    rating_complete: bool | None
    newest_song_time: int


class AllAlbumsPaginated(TypedDict):
    data: list[AlbumInList]
    has_next: bool
    next: int
    progress: int


class AllSongsSong(TypedDict):
    album_name: str
    fave: bool | None
    id: int
    rating: int | None
    rating_user: int | None
    title: str


class AllStationsInfo(TypedDict):
    pass


type AlreadyVotedEntry = tuple[int, int]


class ApiInfo(TypedDict):
    exectime: int
    time: int


class Artist(TypedDict):
    id: int
    name: str


class ArtistInList(TypedDict):
    id: int
    name: str
    song_count: int


class BooleanResult(TypedDict):
    success: bool
    tl_key: str
    text: str


type BuildVersion = int


type CookieDomain = str


type DeleteRequestResult = BooleanResult


type ErrorReportResult = BooleanResult


class FaveAlbumResult(TypedDict):
    id: int
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class FaveAllSongsResult(TypedDict):
    song_ids: list[int]
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class FaveSong(TypedDict):
    album_id: int
    album_name: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    title: str


class FaveSongResult(TypedDict):
    id: int
    fave: bool
    sid: int
    success: bool
    tl_key: str
    text: str


class GroupInList(TypedDict):
    id: int
    name: str


class GroupWithDetail(TypedDict):
    id: int
    name: str
    all_songs_for_sid: dict[str, Any]


class ListenerRatingSpreadItem(TypedDict):
    ratings: int
    rating: int


class ListenerRatingsByStation(TypedDict):
    sid: int
    average_rating: str
    ratings: int


class ListenerRequestsByStation(TypedDict):
    sid: int
    requests: int


class ListenerTopAlbum(TypedDict):
    id: int
    name: str
    rating_listener: int
    rating: int


class ListenerTopRequestAlbum(TypedDict):
    id: int
    name: str
    request_count_listener: int


class ListenerVotesByStation(TypedDict):
    sid: int
    votes: int


class LiveVoting(TypedDict):
    pass


type Locale = str


class Locales(TypedDict):
    pass


class MessageId(TypedDict):
    message_id: int


type Mobile = bool


class NativeError(TypedDict):
    name: str
    message: str
    stack: NotRequired[str]


type OnDraw = list[Any]


type OnInit = list[Any]


type OnMeasure = list[Any]


type OrderRequestsResult = BooleanResult


type PauseRequestQueueResult = BooleanResult


class Ping(TypedDict):
    timestamp: int


class PlaybackHistoryEntry(TypedDict):
    album_id: int
    album_name: str
    artist_parseable: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    song_played_at: int
    title: str


class Pong(TypedDict):
    timestamp: int


class PongConfirm(TypedDict):
    timestamp: int


class RainwaveErrorObject(TypedDict):
    status: int
    tl_key: str
    text: NotRequired[str]
    success: NotRequired[bool]


class Album1(TypedDict):
    id: int
    name: str
    rating: int | None
    fave: bool | None
    rating_user: int | None
    art: str | None


class RainwaveEventSongArtist(TypedDict):
    order: int
    id: int
    name: str


class RainwaveSdkErrorClear(TypedDict):
    tl_key: str


class RedownloadM3u(TypedDict):
    tl_key: str
    text: str


class Relay(TypedDict):
    name: str
    protocol: str
    hostname: str
    port: int


type Relays = list[Relay]


class RequestAlbum(TypedDict):
    name: str
    id: int
    rating: int | None
    rating_user: int | None
    rating_complete: bool | None
    art: str | None


type RequestFavoritedSongsResult = BooleanResult


class RequestLineEntry(TypedDict):
    username: str
    user_id: int
    line_expiry_tune_in: int | None
    line_expiry_election: int | None
    line_wait_start: int
    line_has_had_valid: bool
    song_id: int | None
    skip: bool
    position: int


type RequestResult = BooleanResult


type RequestUnratedSongsResult = BooleanResult


type SdkErrorClear = RainwaveSdkErrorClear


type SdkException = NativeError


type SdkScheduleSynced = bool


class SearchAlbum(TypedDict):
    id: int
    name: str
    cool: bool
    rating: int | None
    fave: bool | None
    rating_user: int | None
    rating_complete: bool | None


class SearchArtist(TypedDict):
    id: int
    name: str


class SearchSong(TypedDict):
    added_on: int
    album_id: int
    album_name: str
    cool_end: int
    cool: bool
    origin_sid: int
    requestable: bool
    id: int
    rating: int
    fave: bool | None
    rating_user: int | None
    title: str
    length: int
    link_text: str | None
    url: str | None


class SongGroup(TypedDict):
    id: int
    name: str


class Album2(TypedDict):
    id: int
    name: str


class SongOnAlbum(TypedDict):
    origin_sid: int
    added_on: int
    cool_multiply: NotRequired[int]
    cool_override: NotRequired[int | None]
    requestable: bool
    cool: bool
    cool_end: int
    request_only_end: int
    request_only: bool
    albums: tuple[Album2]
    artists: list[Artist]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


class AlbumItem(TypedDict):
    id: int
    name: str
    rating: int | None
    fave: bool | None
    rating_user: int | None
    art: str | None
    rating_complete: bool | None


class SongWithDetailArtist(TypedDict):
    order: int
    id: int
    name: str


type Songs = list[SearchSong]


class StationDescription(TypedDict):
    description: str
    id: int
    name: str
    relays: Relays
    stream: str


class StationList(TypedDict):
    pass


class StationSongCountByStation(TypedDict):
    sid: int
    song_count: int


type Stations = list[StationDescription]


type StreamFilename = str


type SyncResult = RainwaveErrorObject


class Top100Song(TypedDict):
    album_name: str
    id: int
    origin_sid: int
    song_rating: int
    song_rating_count: int
    title: str


type Traceback = str


type UnpauseRequestQueueResult = BooleanResult


class UnratedSong(TypedDict):
    album_name: str
    id: int
    title: str


type UnratedSongs = list[UnratedSong]


class UpdatedAlbumRating(TypedDict):
    sid: int
    id: int
    rating_user: int | None
    rating_complete: bool | None


class User(TypedDict):
    admin: bool
    avatar: NotRequired[str | None]
    id: int
    listen_key: str | None
    listener_id: int | None
    lock_counter: int
    lock_in_effect: bool
    lock_sid: int | None
    lock: bool
    name: str
    new_privmsg: int
    perks: bool
    rate_anything: bool
    request_expires_at: int | None
    request_position: int | None
    requests_paused: bool
    sid: int
    tuned_in: bool
    voted_entry: int | None


type UserInfo = User


class UserRecentVote(TypedDict):
    album_name: str
    fave: bool | None
    id: int
    rating: int
    rating_user: int | None
    title: str


type UserRecentVotes = list[UserRecentVote]


type UserRequestedHistory = UserRecentVotes


class VoteResult(TypedDict):
    elec_id: int
    entry_id: int
    success: bool
    tl_key: str
    text: str


type WebsocketHost = str


class AlbumWithDetail(TypedDict):
    genres: list[SongGroup]
    rating_complete: bool | None
    rating_rank: int
    rating_rank_percentile: int
    request_count: int
    request_rank: int
    request_rank_percentile: int
    rating_histogram: dict[str, Any]
    songs: list[SongOnAlbum]
    added_on: int
    art: str | None
    cool_lowest: int
    cool_multiply: NotRequired[int]
    cool_override: NotRequired[int | None]
    cool: bool
    fave_count: int
    fave: bool | None
    id: int
    name: str
    played_last: int
    rating_count: int
    rating_user: int | None
    rating: int | None
    song_count: int
    vote_count: int


type Albums = list[SearchAlbum]


class AllArtistsPaginated(TypedDict):
    data: list[ArtistInList]
    has_next: bool
    next: int
    progress: int


type AllFaves = list[FaveSong]


class AllGroupsPaginated(TypedDict):
    data: list[GroupInList]
    has_next: bool
    next: int
    progress: int


type AllSongs = list[AllSongsSong]


type AlreadyVoted = list[AlreadyVotedEntry]


type Artists = list[SearchArtist]


type Error = RainwaveErrorObject


type Group = GroupWithDetail


class Listener(TypedDict):
    user_id: int
    name: str
    avatar: str | None
    colour: str
    rank: str
    total_votes: int
    total_ratings: int
    mind_changes: int
    total_requests: int
    winning_votes: int
    losing_votes: int
    regdate: int
    top_albums: list[ListenerTopAlbum]
    top_request_albums: list[ListenerTopRequestAlbum]
    votes_by_station: list[ListenerVotesByStation]
    requests_by_station: list[ListenerRequestsByStation]
    requests_by_source_station: list[ListenerRequestsByStation]
    ratings_by_station: list[ListenerRatingsByStation]
    ratings_completion: dict[str, Any]
    rating_spread: list[ListenerRatingSpreadItem]


type PlaybackHistory = list[PlaybackHistoryEntry]


class RainwaveEventSong(TypedDict):
    albums: tuple[Album1]
    artists: list[RainwaveEventSongArtist]
    cool: bool
    elec_blocked_by: str | None
    elec_blocked: bool
    elec_request_user_id: int | None
    elec_request_username: str | None
    entry_id: int
    entry_position: int
    entry_type: Literal[2, 4]
    entry_votes: int
    groups: list[SongGroup]
    origin_sid: int
    rating_allowed: bool
    rating_count: int
    request_id: NotRequired[int | None]
    request_count: int
    sid: int
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


class RateResult(TypedDict):
    updated_album_ratings: list[UpdatedAlbumRating]
    song_id: int
    rating_user: int | None
    success: bool
    tl_key: str
    text: str


class Request(TypedDict):
    albums: tuple[RequestAlbum]
    cool_end: int
    cool: bool
    elec_blocked_by: str | None
    elec_blocked_num: int | None
    elec_blocked: bool
    good: bool
    order: int
    origin_sid: int
    request_id: int
    sid: int
    valid: bool
    artists: list[Artist]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


type RequestLine = list[RequestLineEntry]


type Requests = list[Request]


class SongWithDetail(TypedDict):
    album: tuple[AlbumItem]
    artists: list[SongWithDetailArtist]
    cool: bool
    elec_blocked_by: str | None
    elec_blocked: bool
    groups: list[SongGroup]
    origin_sid: int
    rating_allowed: bool
    rating_count: int
    rating_rank_percentile: int
    rating_rank: int
    request_count: int
    request_rank_percentile: int
    request_rank: int
    sid: int
    albums: tuple[Album2]
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating_user: int | None
    rating: int
    title: str
    url: str | None


type StationSongCount = list[StationSongCountByStation]


type Top100 = list[Top100Song]


type Album = AlbumWithDetail


class RainwaveEvent(TypedDict):
    id: int
    start: int
    start_actual: int | None
    end: int
    type: Literal['Election', 'OneUp', 'PVPElection']
    name: str | None
    sid: int
    url: str | None
    voting_allowed: bool
    used: bool
    length: int
    core_event_id: int | None
    songs: list[RainwaveEventSong]


type SchedCurrent = RainwaveEvent


type SchedHistory = list[RainwaveEvent]


type SchedNext = list[RainwaveEvent]


type Song = SongWithDetail
