# generated by datamodel-codegen:
#   filename:  rainwave-openapi.json
#   timestamp: 2026-03-22T11:51:42+00:00

from typing import Any, Literal, NotRequired, TypedDict

type AlbumArt = str | None


class Artist(TypedDict):
    id: int
    name: str


class ArtistInList(TypedDict):
    id: int
    name: str
    song_count: int


class ArtistWithOrder(TypedDict):
    id: int
    name: str
    order: int


type ElecBlockedBy = Literal['in_election', 'album', 'group'] | None


type ElectionSongType = Literal[2, 4]


class ListenerRatingSpreadItem(TypedDict):
    rating: NotRequired[float]
    ratings: NotRequired[int]


class ListenerTopAlbum(TypedDict):
    id: int
    name: str
    rating: float
    rating_listener: float


class ListenerTopRequestAlbum(TypedDict):
    id: int
    name: str
    request_count_listener: int


class LiveVotingEntry(TypedDict):
    entry_id: int
    entry_votes: int
    song_id: int


type Rating = float


RatingHistogram = TypedDict(
    'RatingHistogram',
    {
        '1.0': int,
        '1.5': int,
        '2.0': int,
        '2.5': int,
        '3.0': int,
        '3.5': int,
        '4.0': int,
        '4.5': int,
        '5.0': int,
    },
)


type RatingUser = float | None


class Relay(TypedDict):
    hostname: str
    name: str
    port: int
    protocol: str


class RequestAlbum(TypedDict):
    art: AlbumArt
    id: int
    name: str
    rating: float
    rating_complete: bool
    rating_user: RatingUser


class RequestLineEntrySong1(TypedDict):
    album_name: str
    id: int
    title: str


type RequestLineEntrySong = RequestLineEntrySong1 | None


class SearchAlbum(TypedDict):
    cool: bool
    fave: bool
    id: int
    name: str
    rating: float
    rating_complete: bool
    rating_user: RatingUser


class SearchArtist(TypedDict):
    id: int
    name: str


class SongBare(TypedDict):
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating: float
    rating_user: RatingUser
    title: str
    url: str | None


class SongBareAlbum(TypedDict):
    albums: list[Any]


class SongBareArtist(TypedDict):
    artists: list[Artist]


class SongGroup(TypedDict):
    id: int
    name: str


type StationId = int


class StationListStation(TypedDict):
    id: int
    url: str


type Time = int


type TimelineEntryType = Literal['Election', 'OneUp', 'PVPElection']


class TimelineSong(SongBare):
    albums: list[Any]
    artists: list[ArtistWithOrder]
    cool: bool
    elec_blocked: bool
    elec_blocked_by: ElecBlockedBy
    elec_request_user_id: int | None
    elec_request_username: str | None
    entry_id: int
    entry_position: int
    entry_type: ElectionSongType
    entry_votes: int
    groups: list[SongGroup]
    origin_sid: StationId
    rating_allowed: bool
    rating_count: int
    request_count: int
    request_id: NotRequired[int | None]
    sid: StationId


class TimelineSongAlbum(TypedDict):
    art: AlbumArt
    fave: bool
    id: int
    name: str
    rating: float
    rating_user: RatingUser


class UpdatedAlbumRating(TypedDict):
    id: int
    rating_complete: bool
    rating_user: RatingUser
    sid: StationId


class UserRecentVote(TypedDict):
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser
    title: str


class AlbumDiffItem(TypedDict):
    cool: NotRequired[bool]
    cool_lowest: NotRequired[Time]
    id: NotRequired[int]
    newest_song_time: NotRequired[Time]


type AlbumDiff = list[AlbumDiffItem]


type Albums = list[SearchAlbum]


class AllArtistsPaginated(TypedDict):
    data: list[ArtistInList]
    has_more: bool
    next: int
    progress: int


class AllFave(TypedDict):
    album_id: int
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser
    title: str


type AllFaves = list[AllFave]


class AllGroupsPaginated(TypedDict):
    data: list[SongGroup]
    has_more: bool
    next: int
    progress: int


class AllSong(TypedDict):
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser
    title: str


type AllSongs = list[AllSong]


type AlreadyVoted = list[list[Any]]


class ApiInfo(TypedDict):
    exectime: float
    time: Time


type ArtistDetail = Any


type Artists = list[SearchArtist]


type BuildVersion = int


type CookieDomain = str


RatingsCompletion = TypedDict(
    'RatingsCompletion',
    {
        '1': int,
        '2': int,
        '3': int,
        '4': int,
        '6': int,
    },
)


type LiveVoting = dict[str, list[LiveVotingEntry]]


type Locale = str


type Locales = dict[str, str]


class MessageId(TypedDict):
    message_id: int


class PowerHour(TypedDict):
    end: Time
    id: int
    name: str
    sid: StationId
    start: Time
    url: str | None


type PowerHours = list[PowerHour]


type Relays = list[Relay]


class Request(SongBare, SongBareArtist):
    albums: list[Any]
    cool: bool
    cool_end: Time | None
    elec_blocked: bool
    elec_blocked_by: ElecBlockedBy
    elec_blocked_num: float | None
    good: bool
    order: int
    origin_sid: StationId
    request_id: int
    sid: StationId
    valid: bool


type Requests = list[Request]


class Song(TypedDict):
    album: list[Any]
    artists: list[ArtistWithOrder]
    cool: bool
    elec_blocked: bool
    elec_blocked_by: ElecBlockedBy
    groups: list[SongGroup]
    origin_sid: StationId
    rating_allowed: bool
    rating_count: int
    rating_rank: int
    rating_rank_percentile: int
    request_count: int
    request_rank: int
    request_rank_percentile: int
    sid: StationId
    rating_histogram: NotRequired[RatingHistogram]


class SearchSong(SongBare):
    added_on: Time
    album_id: int
    album_name: str
    cool: bool
    cool_end: Time | None
    origin_sid: StationId
    requestable: bool


type Songs = list[SearchSong]


StationList = TypedDict(
    'StationList',
    {
        '1': NotRequired[StationListStation],
        '2': NotRequired[StationListStation],
        '3': NotRequired[StationListStation],
        '4': NotRequired[StationListStation],
        '5': NotRequired[StationListStation],
        '6': NotRequired[StationListStation],
    },
)


class StationSongCountItem(TypedDict):
    sid: StationId
    song_count: int


type StationSongCount = list[StationSongCountItem]


class Station(TypedDict):
    description: str
    id: StationId
    name: str
    relays: Relays
    stream: str


type Stations = list[Station]


type StreamFilename = str


class TipJarItem(TypedDict):
    amount: float
    id: int
    message: str | None
    name: str | None


type TipJar = list[TipJarItem]


class Top100Item(TypedDict):
    album_name: str
    id: int
    origin_sid: StationId
    song_rating: float
    song_rating_count: int
    title: str


type Top100 = list[Top100Item]


class UnratedSong(TypedDict):
    album_name: str
    id: int
    title: str


type UnratedSongs = list[UnratedSong]


class User(TypedDict):
    admin: bool
    avatar: str | None
    id: int
    listen_key: str | None
    listener_id: int | None
    lock: bool
    lock_counter: int
    lock_in_effect: bool
    lock_sid: StationId | None
    name: str
    new_privmsg: int
    perks: bool
    rate_anything: bool
    request_expires_at: Time | None
    request_position: int | None
    requests_paused: bool
    sid: StationId
    tuned_in: bool
    voted_entry: int | None


class UserInfo(User):
    pass


type UserRecentVotes = list[UserRecentVote]


type UserRequestedHistory = list[UserRecentVote]


type WebsocketHost = str


type Wsok = bool


class AdminUserSearchResult(TypedDict):
    user_id: int | None
    sid: int | None


class AdminJsError(TypedDict):
    user_id: int
    username: str
    time: int
    name: str
    message: str
    lineNumber: int | str | None
    columnNumber: int | str | None
    stack: str
    location: str
    userAgent: str
    browserLanguage: str


type AdminJsErrors = list[AdminJsError]


class AdminMusicScanError(TypedDict):
    time: int
    file: str
    type: str
    error: str
    traceback: str


type AdminMusicScanErrors = list[AdminMusicScanError]


class AdminPowerHourSong(TypedDict):
    one_up_id: int
    sched_id: int
    song_id: int
    one_up_order: int | None
    one_up_used: bool
    one_up_queued: bool
    one_up_sid: int
    one_up_start_actual: int | None
    song_title: str
    album_name: str
    album_id: int
    song_length: int


class AdminPowerHour(TypedDict):
    sched_start: int | None
    sched_end: int | None
    sched_type: str
    sched_name: str | None
    sched_url: str | None
    sid: int
    sched_timed: bool
    sched_creator_user_id: int | None
    sched_id: int
    sched_start_actual: int | None
    sched_end_actual: int | None
    sched_used: bool
    songs: NotRequired[list[AdminPowerHourSong]]


type AdminPowerHours = list[AdminPowerHour]


type TranslationKey = Literal[
    '#_requests',
    '404',
    'Albums',
    'Artists',
    'Artists_pluralized',
    'Cancel',
    'Clear',
    'Faves',
    'Filter...',
    'Groups',
    'Listeners',
    'Loading...',
    'Patreon',
    'Pause',
    'PayPal',
    'Rate',
    'Request',
    'RequestLine',
    'Requests',
    'Resume',
    'Settings',
    'Songs',
    'Suspend',
    'Unrated',
    'Users',
    'admin_required',
    'album_all_cooldown',
    'album_does_not_exist',
    'album_has_cooldown',
    'album_id',
    'album_name',
    'album_on_other_station',
    'album_on_station',
    'album_rating_detail',
    'album_rating_ranked_at_v2',
    'album_requests_ranked_at',
    'all_faves',
    'allow_api_auth',
    'already_voted_for_song',
    'amount',
    'api_docs',
    'api_key',
    'api_key_manager',
    'app_would_like_to',
    'async_error',
    'audio_connect_error',
    'audio_connect_error_reattempting',
    'audio_error',
    'auth_failed',
    'auth_failed_message',
    'auth_required',
    'average_rating_by_station',
    'basic',
    'blocked_by_name__album',
    'blocked_by_name__group',
    'blocked_by_name__in_election',
    'cannot_rate_now',
    'cannot_vote_for_this_now',
    'cd_album',
    'cd_album_length',
    'cd_album_size',
    'cd_blue_bkg_is',
    'cd_category',
    'cd_category_length',
    'cd_cooldown_length',
    'cd_cooldowns_depend_on',
    'cd_example',
    'cd_higher_rating',
    'cd_larger_album',
    'cd_newer',
    'cd_rating',
    'cd_recently_added',
    'cd_song',
    'cd_song_length',
    'cd_type_of_cooldown',
    'cd_what_is',
    'cd_why_use_cooldown',
    'change_language',
    'chat',
    'chrome_mobile_takes_time',
    'clear_request_queue',
    'coming_up',
    'continued',
    'cool_end',
    'crash_happened',
    'create_api_key',
    'db_error_permanent',
    'db_error_retry',
    'debug_information',
    'deeplink_error',
    'delete',
    'discord_already_associated',
    'election',
    'empty_list',
    'end',
    'event_naming__oneup',
    'fave',
    'fave_all_songs',
    'fave_failed',
    'font_options',
    'forums',
    'full',
    'github_repo',
    'go',
    'groups_tab_title',
    'hold_to_rate',
    'hotkey_mode',
    'hotkeys_fave',
    'hotkeys_play',
    'hotkeys_rate05',
    'hotkeys_rate10',
    'hotkeys_vote0',
    'hotkeys_vote1',
    'id',
    'internal_error',
    'invalid_argument',
    'invalid_hotkey',
    'invalid_hotkey_vote',
    'invalid_request',
    'invalid_station_id',
    'language_name',
    'language_name_short',
    'legacy_username',
    'library',
    'link_discord',
    'listen_via_browser',
    'listen_via_mp3',
    'listen_via_ogg',
    'locked_to_station',
    'login',
    'login_failed',
    'login_limit',
    'login_password_disabled',
    'login_required',
    'login_too_old',
    'login_with_legacy',
    'logout',
    'lost_connection',
    'm3u_hijack_right_click',
    'make_a_request',
    'message',
    'missing_argument',
    'missing_station_id',
    'mobile_sync_retrying',
    'must_login_and_tune_in_to_request',
    'name',
    'new_album',
    'new_songs',
    'newish_album',
    'newish_songs',
    'no',
    'no_ratings',
    'no_results',
    'no_search_results',
    'no_song_selected',
    'no_songs_on_this_station',
    'nobody_in_line',
    'not_an_election',
    'now_playing',
    'now_playing_on_...',
    'num_votes',
    'oauth_rejected',
    'oops',
    'origin_sid',
    'page_title_on_google',
    'password',
    'password_required',
    'pause_request_queue',
    'perks_required',
    'playback_history',
    'playback_history_link',
    'played_ago',
    'playlist',
    'playlist_preferences',
    'please_refresh',
    'power_hour',
    'power_hours',
    'preferences',
    'prefs_f_norm',
    'prefs_hkm',
    'prefs_l_displose',
    'prefs_l_stksz',
    'prefs_notify',
    'prefs_p_avup',
    'prefs_p_fav1',
    'prefs_p_favup',
    'prefs_p_null1',
    'prefs_p_songsort',
    'prefs_p_sort',
    'prefs_pwr',
    'prefs_r_clear',
    'prefs_r_incmplt',
    'prefs_r_noglbl',
    'prefs_roboto',
    'prefs_sort_playlist_by_alpha',
    'prefs_sort_playlist_by_rating_user',
    'prefs_t_clk',
    'prefs_t_rt',
    'prefs_t_tl',
    'previouslyplayed',
    'qr_code',
    'random_relay',
    'rate_song_mobile_dialog',
    'rating',
    'rating_cleared',
    'rating_counts_across_stations',
    'rating_detail_numbers',
    'rating_percentile_bottom',
    'rating_percentile_top',
    'rating_preferences',
    'rating_spread',
    'rating_submitted',
    'rating_user',
    'ratings_completion_rate',
    'recent_votes',
    'redownload_m3u',
    'register_with_discord',
    'registered_in_year',
    'relevant_categories',
    'relevant_categories_rollover',
    'relevant_category',
    'report_error',
    'report_sending',
    'report_sent',
    'report_submitted',
    'request_delete_failed',
    'request_deleted',
    'request_failed',
    'request_favorited_failed',
    'request_favorited_songs_success',
    'request_fill_with_faves',
    'request_fill_with_unrated',
    'request_grab_tag__paused',
    'request_history',
    'request_in_election',
    'request_on_cooldown_ends_soon',
    'request_on_cooldown_for',
    'request_only_on_x',
    'request_percentile_bottom',
    'request_percentile_top',
    'request_queue_paused',
    'request_queue_unpaused',
    'request_success',
    'request_unrated_failed',
    'request_unrated_songs_success',
    'request_you_are_x_in_line',
    'requests_all_on_cooldown',
    'requests_by_source_station',
    'requests_by_station',
    'requests_reordered',
    'same_request_album',
    'same_request_exists',
    'search',
    'search...',
    'search_result_limit',
    'search_string_too_short',
    'server_just_started',
    'sid',
    'signup',
    'site_mode',
    'something_went_wrong',
    'song_does_not_exist',
    'song_has_no_ratings',
    'song_id',
    'song_not_requested',
    'song_on_other_station',
    'song_rating',
    'song_rating_count',
    'song_rating_detail',
    'songs_from',
    'special_event_alert',
    'start',
    'station_description_id_1',
    'station_description_id_2',
    'station_description_id_3',
    'station_description_id_4',
    'station_description_id_5',
    'station_description_id_6',
    'station_menu_description_id_1',
    'station_menu_description_id_2',
    'station_menu_description_id_3',
    'station_menu_description_id_4',
    'station_menu_description_id_5',
    'station_menu_description_id_6',
    'station_name_1',
    'station_name_2',
    'station_name_3',
    'station_name_4',
    'station_name_5',
    'station_name_6',
    'station_offline',
    'station_select_header',
    'stop',
    'success',
    'sync_retrying',
    'sync_stopped',
    'tab_title_preferences',
    'timeformat_d',
    'timeformat_h',
    'timeformat_m',
    'timeformat_s',
    'timeformat_w',
    'timeline_art__request_indicator',
    'timeline_art__your_request_indicator',
    'timeline_preferences',
    'tip_jar',
    'tip_jar_all_donations',
    'tip_jar_balance',
    'tip_jar_instruction_1',
    'tip_jar_instruction_2',
    'tip_jar_instruction_3',
    'tip_jar_opener',
    'tip_jar_opener_end',
    'title',
    'too_many_requests',
    'top_100',
    'top_rated_albums',
    'top_requested_albums',
    'try_external_player',
    'tunein',
    'tunein_required',
    'tunein_to_rate_current_song',
    'unfave_all_songs',
    'unknown_error_message',
    'unlocked_only',
    'unpause_request_queue',
    'unrated_songs',
    'user_id',
    'user_locked',
    'user_recent_votes',
    'user_requested_history',
    'username_required',
    'view_your',
    'vote',
    'vote_now',
    'vote_submitted',
    'voted',
    'votes_by_source_station',
    'votes_by_station',
    'waiting_for_hotkey',
    'websocket_throttle',
    'yes',
    'your_album_rating',
    'your_numeric_user_id',
]


class AlbumCore(TypedDict):
    added_on: Time
    art: str | None
    cool: bool
    cool_lowest: Time
    fave: bool
    fave_count: int
    id: int
    name: str
    played_last: Time
    rating: float | None
    rating_count: int
    rating_user: RatingUser
    request_count: float
    song_count: float
    vote_count: float


class AlbumInList(TypedDict):
    cool: bool
    cool_lowest: Time
    fave: bool
    id: int
    name: str
    newest_song_time: Time
    rating: float
    rating_complete: bool
    rating_user: RatingUser


class BooleanResult(TypedDict):
    success: bool
    text: str
    tl_key: TranslationKey


class Error(TypedDict):
    code: NotRequired[float]
    success: NotRequired[bool]
    text: str
    tl_key: TranslationKey
    traceback: NotRequired[str]


class ListenerRatingsByStation(TypedDict):
    average_rating: str
    ratings: int
    sid: StationId


class ListenerRequestsByStation(TypedDict):
    requests: int
    sid: StationId


class ListenerVotesByStation(TypedDict):
    sid: StationId
    votes: int


class PlaybackHistoryEntry(TypedDict):
    album_id: int
    album_name: str
    artist_parseable: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser
    song_played_at: Time
    title: str


class RequestLineEntry(TypedDict):
    line_expiry_election: Time | None
    line_expiry_tune_in: Time | None
    line_has_had_valid: bool
    line_wait_start: Time
    position: int
    skip: bool
    song: NotRequired[RequestLineEntrySong]
    song_id: int | None
    user_id: int
    username: str


class SongInArtist(SongBare, SongBareAlbum):
    cool: bool
    requestable: bool
    sid: StationId


class SongOnAlbum(SongBare):
    artist_parseable: str
    added_on: Time
    cool: bool
    cool_end: Time
    origin_sid: StationId
    requestable: bool


class StationInfo(TypedDict):
    album: str
    art: AlbumArt
    artists: str
    event_name: str | None
    event_type: TimelineEntryType | None
    title: str


class TimelineEntry(TypedDict):
    end: Time
    id: int
    length: int
    name: str | None
    sid: StationId
    songs: list[TimelineSong]
    start: Time
    start_actual: Time | None
    type: TimelineEntryType
    url: str | None
    used: bool
    voting_allowed: bool


class Album(TypedDict):
    added_on: Time
    art: AlbumArt
    cool_lowest: Time
    cool: bool
    fave_count: int
    fave: bool
    id: int
    name: str
    played_last: Time
    rating_count: int
    rating_user: RatingUser
    rating: float | None
    song_count: int
    vote_count: int
    genres: list[SongGroup]
    rating_complete: bool
    rating_histogram: RatingHistogram
    rating_rank: int
    rating_rank_percentile: int
    request_count: int
    request_rank: int
    request_rank_percentile: int
    songs: list[SongOnAlbum]


class AllAlbumsPaginated(TypedDict):
    data: list[AlbumInList]
    has_more: bool
    next: int
    progress: int


AllStationsInfo = TypedDict(
    'AllStationsInfo',
    {
        '1': StationInfo,
        '2': StationInfo,
        '3': StationInfo,
        '4': StationInfo,
        '5': StationInfo,
        '6': StationInfo,
    },
)


AllSongsForArtist = TypedDict(
    'AllSongsForArtist',
    {
        '1': NotRequired[dict[str, list[SongInArtist]]],
        '2': NotRequired[dict[str, list[SongInArtist]]],
        '3': NotRequired[dict[str, list[SongInArtist]]],
        '4': NotRequired[dict[str, list[SongInArtist]]],
        '5': NotRequired[dict[str, list[SongInArtist]]],
        '6': NotRequired[dict[str, list[SongInArtist]]],
    },
)


class Artist1(Artist):
    all_songs: NotRequired[AllSongsForArtist]


class DeleteRequestResult(BooleanResult):
    pass


class Error1(Error):
    pass


class ErrorReportResult(BooleanResult):
    pass


class FaveAlbumResult(BooleanResult):
    fave: bool
    id: int
    sid: StationId


class FaveAllSongsResult(BooleanResult):
    fave: bool
    sid: StationId
    song_ids: list[int]


class FaveSongResult(BooleanResult):
    fave: bool
    id: int
    sid: StationId


class Group(SongGroup):
    all_songs_for_sid: dict[str, dict[str, list[SongInArtist]]]


class Listener(TypedDict):
    avatar: str | None
    colour: str | None
    losing_votes: int
    mind_changes: int
    name: str
    rank: str | None
    rating_spread: list[ListenerRatingSpreadItem]
    ratings_by_station: list[ListenerRatingsByStation]
    ratings_completion: RatingsCompletion
    regdate: Time
    requests_by_source_station: list[ListenerRequestsByStation]
    requests_by_station: list[ListenerRequestsByStation]
    top_albums: list[ListenerTopAlbum]
    top_request_albums: list[ListenerTopRequestAlbum]
    total_ratings: int
    total_requests: int
    total_votes: int
    user_id: int
    votes_by_station: list[ListenerVotesByStation]
    winning_votes: int


type OrderRequestsResult = BooleanResult


type PauseRequestQueueResult = BooleanResult


type PlaybackHistory = list[PlaybackHistoryEntry]


class RateResult(BooleanResult):
    rating_user: RatingUser
    song_id: int
    updated_album_ratings: list[UpdatedAlbumRating]


class RedownloadM3u(TypedDict):
    text: str
    tl_key: TranslationKey


type RequestFavoritedSongsResult = BooleanResult


type RequestLine = list[RequestLineEntry]


type RequestResult = BooleanResult


type RequestUnratedSongsResult = BooleanResult


class SchedCurrent(TimelineEntry):
    pass


type SchedHistory = list[TimelineEntry]


type SchedNext = list[TimelineEntry]


type SyncResult = Error


type UnpauseRequestQueueResult = BooleanResult


class VoteResult(BooleanResult):
    elec_id: int | None
    entry_id: int


type Wserror = Error


class Wsthrottle(TypedDict):
    text: str
    tl_key: TranslationKey


class UpdateUserNicknameByDiscordIdResult(BooleanResult):
    pass


class UpdateUserAvatarByDiscordIdResult(BooleanResult):
    pass


class EnablePerksByDiscordIdsResult(BooleanResult):
    pass


class AddDonationResult(BooleanResult):
    pass


class DeletePowerHourResult(BooleanResult):
    pass


class SetSongRequestOnlyResult(BooleanResult):
    pass


class SetSongCooldownResult(BooleanResult):
    pass


class SetAlbumCooldownResult(BooleanResult):
    pass
