# generated by datamodel-codegen:
#   filename:  tmp.fIRdGhMd9r
#   timestamp: 2026-04-11T15:07:50+00:00

from pydantic import BaseModel, Field, RootModel
from enum import StrEnum
from typing import Any


class Api4AdminAddAlbumToPowerHourPostRequest(BaseModel):
    sched_id: int
    album_id: int


class Api4AdminAddDonationPostRequest(BaseModel):
    donor_id: int
    amount: float
    message: str
    private: bool


class Api4AdminAddSongToPowerHourPostRequest(BaseModel):
    sched_id: int
    song_id: int


class Api4AdminChangePowerHourNamePostRequest(BaseModel):
    sched_id: int
    name: str


class Api4AdminChangePowerHourStartTimePostRequest(BaseModel):
    sched_id: int
    utc_time: int


class Api4AdminChangePowerHourUrlPostRequest(BaseModel):
    sched_id: int
    url: str | None


class Api4AdminCreatePowerHourPostRequest(BaseModel):
    name: str
    start_utc_time: int
    end_utc_time: int
    url: str | None
    fill_unrated: bool | None
    sid: int


class Api4AdminDeletePowerHourPostRequest(BaseModel):
    sched_id: int


class Api4AdminDuplicatePowerHourPostRequest(BaseModel):
    sched_id: int


class Api4AdminEuropifyPowerHourPostRequest(BaseModel):
    sched_id: int


class Api4AdminOrderPowerHourSongsPostRequest(BaseModel):
    sched_id: int
    order: str = Field(
        ...,
        description='A comma-separated list of one_up_id values that represent the Power Hour song queue, in the order the admin desires.',
    )


class Api4AdminPowerHourPostRequest(BaseModel):
    sched_id: int


class Api4AdminPowerHourRemoveSongPostRequest(BaseModel):
    one_up_id: int


class Api4AdminResetAlbumCooldownPostRequest(BaseModel):
    album_id: int


class Api4AdminResetSongCooldownPostRequest(BaseModel):
    song_id: int


class Api4AdminSetAlbumCooldownPostRequest(BaseModel):
    album_id: int
    multiply: float | None
    override: int | None


class Api4AdminSetSongCooldownPostRequest(BaseModel):
    song_id: int
    multiply: float | None
    override: int | None


class Api4AdminSetSongRequestOnlyPostRequest(BaseModel):
    song_id: int
    request_only: bool
    sid: int


class Api4AdminAlbumArtPostRequest(BaseModel):
    album_id: int


class Api4AdminAlbumSongsPostRequest(BaseModel):
    sid: int
    album_id: int


class Api4AdminAlbumsPostRequest(BaseModel):
    sid: int


class Api4AdminShufflePowerHourPostRequest(BaseModel):
    sched_id: int


class Api4UpdateUserAvatarByDiscordIdPostRequest(BaseModel):
    discord_user_id: str
    avatar: str


class Api4UpdateUserNicknameByDiscordIdPostRequest(BaseModel):
    discord_user_id: str
    nickname: str


class Api4EnablePerksByDiscordIdsPostRequest(BaseModel):
    discord_user_ids: list[str]


class Api4UserSearchPostRequest(BaseModel):
    username: str


class Api4UserSearchByDiscordUserIdPostRequest(BaseModel):
    discord_user_id: str


class Sort(StrEnum):
    added_on = 'added_on'


class Api4AlbumPostRequest(BaseModel):
    id: int
    sort: Sort | None = Field(
        None, description='How to sort the songs that are a part of the album.'
    )


class Api4AllAlbumsPaginatedPostRequest(BaseModel):
    after: int | None = None


class Api4AllArtistsPaginatedPostRequest(BaseModel):
    after: int | None = None


class Api4AllFavesPostRequest(BaseModel):
    page_start: int | None = None
    per_page: int | None = None


class Api4AllGroupsPostRequest(BaseModel):
    after: int | None = None


class Api4AllGroupsPaginatedPostRequest(BaseModel):
    after: int | None = None


class Order(StrEnum):
    rating = 'rating'


class Api4AllSongsPostRequest(BaseModel):
    order: Order | None = None
    page_start: int | None = None
    per_page: int | None = None


class Api4ArtistPostRequest(BaseModel):
    id: int


class Api4CheckSchedCurrentIdPostRequest(BaseModel):
    sched_id: int = Field(
        ..., description='The last timeline entry sched_id you have seen.'
    )


class Api4CheckSchedCurrentIdPostResponse(BaseModel):
    pass


class Api4AuthPostRequest(BaseModel):
    user_id: int
    key: str


class Api4PingPostRequest(BaseModel):
    pass


class Api4ClearRatingPostRequest(BaseModel):
    song_id: int


class Api4ClearRequestsPostRequest(BaseModel):
    pass


class Api4ClearRequestsOnCooldownPostRequest(BaseModel):
    pass


class Api4DeleteRequestPostRequest(BaseModel):
    song_id: int


class Api4FaveAlbumPostRequest(BaseModel):
    album_id: int
    fave: bool


class Api4FaveAllSongsPostRequest(BaseModel):
    album_id: int
    fave: bool


class Api4FaveSongPostRequest(BaseModel):
    fave: bool
    song_id: int


class Api4GroupPostRequest(BaseModel):
    id: int


class Api4InfoAllPostRequest(BaseModel):
    pass


class Api4ListenerPostRequest(BaseModel):
    id: int


class Api4OrderRequestsPostRequest(BaseModel):
    order: str = Field(
        ...,
        description="A comma-separated list of Song IDs that represent the user's request queue, in the order the user desires.",
    )


class Api4PauseRequestQueuePostRequest(BaseModel):
    pass


class Api4PlaybackHistoryPostRequest(BaseModel):
    page_start: int | None = None
    per_page: int | None = None


class Api4RatePostRequest(BaseModel):
    rating: float
    song_id: int


class Api4RequestPostRequest(BaseModel):
    song_id: int


class Api4RequestFavoritedSongsPostRequest(BaseModel):
    pass


class Api4RequestLinePostRequest(BaseModel):
    pass


class Api4RequestUnratedSongsPostRequest(BaseModel):
    pass


class Api4SearchPostRequest(BaseModel):
    search: str


class Api4SongPostRequest(BaseModel):
    id: int


class Api4StationSongCountPostRequest(BaseModel):
    pass


class Api4UnpauseRequestQueuePostRequest(BaseModel):
    pass


class Api4UnratedSongsPostRequest(BaseModel):
    page_start: int | None = None
    per_page: int | None = None


class Api4UserInfoPostRequest(BaseModel):
    api_key: str | None = None
    user_id: int | None = None


class Api4UserRecentVotesPostRequest(BaseModel):
    page_start: int | None = None
    per_page: int | None = None


class Api4UserRequestedHistoryPostRequest(BaseModel):
    page_start: int | None = None
    per_page: int | None = None


class Api4VotePostRequest(BaseModel):
    entry_id: int


class AdminUserSearchResult(BaseModel):
    user_id: int | None
    sid: int | None


class RatingsCompletion(BaseModel):
    field_1: int = Field(..., alias='1')
    field_2: int = Field(..., alias='2')
    field_3: int = Field(..., alias='3')
    field_4: int = Field(..., alias='4')
    field_6: int = Field(..., alias='6')


class Pong(RootModel[bool]):
    root: bool


class UnratedSong(BaseModel):
    album_name: str
    id: int
    title: str


class UnratedSongs(RootModel[list[UnratedSong]]):
    root: list[UnratedSong]


class Wsok(RootModel[bool]):
    root: bool


class AdminAlbum(BaseModel):
    album_id: int
    album_name: str
    rating: float | None
    rating_count: int
    album_cool_multiply: float | None
    album_cool_override: int | None


class AdminAlbumSong(BaseModel):
    song_id: int
    song_filename: str
    rating: float | None
    rating_count: int
    song_cool_multiply: float | None
    song_cool_override: int | None
    song_request_only: bool


class AdminJsError(BaseModel):
    user_id: int
    username: str
    time: int
    name: str
    message: str
    lineNumber: int | str | None
    columnNumber: int | str | None
    stack: str
    location: str
    userAgent: str
    browserLanguage: str


class AdminMusicScanError(BaseModel):
    time: int
    file: str
    type: str
    error: str
    traceback: str


class AdminPowerHourSong(BaseModel):
    one_up_id: int
    sched_id: int
    song_id: int
    one_up_order: int | None
    one_up_used: bool
    one_up_queued: bool
    one_up_sid: int
    one_up_start_actual: int | None
    song_title: str
    album_name: str
    album_id: int
    song_length: int


class AlbumArt(RootModel[str | None]):
    root: str | None = Field(
        ...,
        description='Base album art URL for Rainwave. Usage: `art = album_art ? "https://rainwave.cc/${albumArt}_320.jpg" : "https://rainwave.cc/static/images4/noart_1.jpg"`',
    )


class Artist(BaseModel):
    id: int
    name: str


class ArtistInList(BaseModel):
    id: int
    name: str
    song_count: int


class ArtistWithOrder(BaseModel):
    id: int
    name: str
    order: int


class ElecBlockedBy1(StrEnum):
    in_election = 'in_election'
    album = 'album'
    group = 'group'


class ElecBlockedBy(RootModel[ElecBlockedBy1 | None]):
    root: ElecBlockedBy1 | None


class ListenerRatingSpreadItem(BaseModel):
    rating: float | None = None
    ratings: int | None = None


class ListenerTopAlbum(BaseModel):
    id: int
    name: str
    rating: float
    rating_listener: float


class ListenerTopRequestAlbum(BaseModel):
    id: int
    name: str
    request_count_listener: int


class RatingHistogram(BaseModel):
    field_1_0: int = Field(..., alias='1.0')
    field_1_5: int = Field(..., alias='1.5')
    field_2_0: int = Field(..., alias='2.0')
    field_2_5: int = Field(..., alias='2.5')
    field_3_0: int = Field(..., alias='3.0')
    field_3_5: int = Field(..., alias='3.5')
    field_4_0: int = Field(..., alias='4.0')
    field_4_5: int = Field(..., alias='4.5')
    field_5_0: int = Field(..., alias='5.0')


class RatingUser(RootModel[float | None]):
    root: float | None


class RequestAlbum(BaseModel):
    art: AlbumArt | None
    id: int
    name: str
    rating: float
    rating_complete: bool
    rating_user: RatingUser | None


class SearchAlbum(BaseModel):
    cool: bool
    fave: bool
    id: int
    name: str
    rating: float
    rating_complete: bool
    rating_user: RatingUser | None


class SearchArtist(BaseModel):
    id: int
    name: str


class SongBare(BaseModel):
    fave: bool | None
    id: int
    length: int
    link_text: str | None
    rating: float
    rating_user: RatingUser | None
    title: str
    url: str | None


class SongBareArtist(BaseModel):
    artists: list[Artist]


class SongGroup(BaseModel):
    id: int
    name: str


class StationId(RootModel[int]):
    root: int


class Time(RootModel[int]):
    root: int = Field(..., description='Epoch Time - seconds since Jan 1st 00:00 1970')


class TranslationKey(RootModel[str]):
    root: str = Field(..., description='Translation key used for localization lookups.')


class UpdatedAlbumRating(BaseModel):
    id: int
    rating_complete: bool
    rating_user: RatingUser | None
    sid: StationId


class UserRecentVote(BaseModel):
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser | None
    title: str


class Relay(BaseModel):
    hostname: str
    name: str
    port: int
    protocol: str


class RequestLineEntrySong1(BaseModel):
    album_name: str
    id: int
    title: str


class RequestLineEntrySong(RootModel[RequestLineEntrySong1 | None]):
    root: RequestLineEntrySong1 | None


class SongBareAlbum(BaseModel):
    albums: list[Any]


class TimelineEntryType(StrEnum):
    Election = 'Election'
    OneUp = 'OneUp'
    PVPElection = 'PVPElection'


class Api4UserSearchPostResponse(BaseModel):
    admin_user_search_result: AdminUserSearchResult


class Api4UserSearchByDiscordUserIdPostResponse(BaseModel):
    admin_user_search_result: AdminUserSearchResult


class Api4AuthPostResponse(BaseModel):
    wsok: Wsok


class Api4PingPostResponse(BaseModel):
    pong: Pong


class Api4UnratedSongsPostResponse(BaseModel):
    unrated_songs: UnratedSongs


class Error(BaseModel):
    code: float | None = None
    success: bool | None = None
    text: str
    tl_key: TranslationKey
    traceback: str | None = None


class AdminAlbumSongs(RootModel[list[AdminAlbumSong]]):
    root: list[AdminAlbumSong]


class AdminAlbums(RootModel[list[AdminAlbum]]):
    root: list[AdminAlbum]


class AdminJsErrors(RootModel[list[AdminJsError]]):
    root: list[AdminJsError]


class AdminMusicScanErrors(RootModel[list[AdminMusicScanError]]):
    root: list[AdminMusicScanError]


class AdminPowerHour(BaseModel):
    sched_start: int | None
    sched_end: int | None
    sched_type: str
    sched_name: str | None
    sched_url: str | None
    sid: int
    sched_timed: bool
    sched_creator_user_id: int | None
    sched_id: int
    sched_start_actual: int | None
    sched_end_actual: int | None
    sched_used: bool
    songs: list[AdminPowerHourSong] | None = None


class AdminPowerHours(RootModel[list[AdminPowerHour]]):
    root: list[AdminPowerHour]


class Albums(RootModel[list[SearchAlbum]]):
    root: list[SearchAlbum]


class AllArtists(RootModel[list[ArtistInList]]):
    root: list[ArtistInList]


class AllArtistsPaginated(BaseModel):
    data: list[ArtistInList]
    has_more: bool
    next: int
    progress: int


class AllFave(BaseModel):
    album_id: int
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser | None
    title: str


class AllFaves(RootModel[list[AllFave]]):
    root: list[AllFave]


class AllGroups(RootModel[list[SongGroup]]):
    root: list[SongGroup]


class AllGroupsPaginated(BaseModel):
    data: list[SongGroup]
    has_more: bool
    next: int
    progress: int


class AllSong(BaseModel):
    album_name: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser | None
    title: str


class AllSongs(RootModel[list[AllSong]]):
    root: list[AllSong]


class Artists(RootModel[list[SearchArtist]]):
    root: list[SearchArtist]


class Request(SongBare, SongBareArtist):
    albums: list[Any]
    cool: bool
    cool_end: Time | None
    elec_blocked: bool
    elec_blocked_by: ElecBlockedBy | None
    elec_blocked_num: float | None
    good: bool = Field(..., description='Does the song still exist on the Rainwave?')
    order: int
    origin_sid: StationId
    request_id: int
    sid: StationId
    valid: bool = Field(
        ..., description='Does the song still exist on the station of the API request?'
    )


class Requests(RootModel[list[Request]]):
    root: list[Request]


class Song(BaseModel):
    album: list[Any]
    artists: list[ArtistWithOrder]
    cool: bool
    elec_blocked: bool
    elec_blocked_by: ElecBlockedBy | None
    groups: list[SongGroup]
    origin_sid: StationId
    rating_allowed: bool
    rating_count: int
    rating_rank: int
    rating_rank_percentile: int
    request_count: int = Field(..., deprecated=True)
    request_rank: int = Field(..., deprecated=True)
    request_rank_percentile: int = Field(..., deprecated=True)
    sid: StationId
    rating_histogram: RatingHistogram | None = None


class StationSongCountItem(BaseModel):
    sid: StationId
    song_count: int


class StationSongCount(RootModel[list[StationSongCountItem]]):
    root: list[StationSongCountItem]


class Top100Item(BaseModel):
    album_name: str
    id: int
    origin_sid: StationId
    song_rating: float
    song_rating_count: int
    title: str


class Top100(RootModel[list[Top100Item]]):
    root: list[Top100Item]


class User(BaseModel):
    admin: bool
    avatar: str | None
    id: int
    listen_key: str | None
    listener_id: int | None
    lock: bool
    lock_counter: int
    lock_in_effect: bool
    lock_sid: StationId | None
    name: str
    new_privmsg: int = Field(..., deprecated=True)
    perks: bool
    rate_anything: bool
    request_expires_at: Time | None
    request_position: int | None
    requests_paused: bool
    sid: StationId
    tuned_in: bool
    voted_entry: int | None


class UserInfo(User):
    pass


class UserRecentVotes(RootModel[list[UserRecentVote]]):
    root: list[UserRecentVote]


class UserRequestedHistory(RootModel[list[UserRecentVote]]):
    root: list[UserRecentVote]


class AdminAlbumArt(BaseModel):
    sid: StationId
    album_art: AlbumArt | None


class AlbumInList(BaseModel):
    cool: bool
    cool_lowest: Time
    fave: bool
    id: int
    name: str
    newest_song_time: Time
    rating: float
    rating_complete: bool
    rating_user: RatingUser | None


class BooleanResult(BaseModel):
    success: bool
    text: str
    tl_key: TranslationKey


class ListenerRatingsByStation(BaseModel):
    average_rating: str
    ratings: int
    sid: StationId


class ListenerRequestsByStation(BaseModel):
    requests: int
    sid: StationId


class ListenerVotesByStation(BaseModel):
    sid: StationId
    votes: int


class PlaybackHistoryEntry(BaseModel):
    album_id: int
    album_name: str
    artist_parseable: str
    fave: bool
    id: int
    rating: float
    rating_user: RatingUser | None
    song_played_at: Time
    title: str


class RequestLineEntry(BaseModel):
    line_expiry_election: Time | None
    line_expiry_tune_in: Time | None
    line_has_had_valid: bool
    line_wait_start: Time
    position: int
    skip: bool
    song: RequestLineEntrySong | None = None
    song_id: int | None
    user_id: int
    username: str


class SearchSong(SongBare):
    added_on: Time
    album_id: int
    album_name: str
    cool: bool
    cool_end: Time | None
    origin_sid: StationId
    requestable: bool


class SongInArtist(SongBare, SongBareAlbum):
    cool: bool
    requestable: bool
    sid: StationId


class SongOnAlbum(SongBare):
    artist_parseable: str
    added_on: Time
    cool: bool
    cool_end: Time
    origin_sid: StationId
    requestable: bool


class StationInfo(BaseModel):
    album: str
    art: AlbumArt | None
    artists: str
    event_name: str | None
    event_type: TimelineEntryType | None
    title: str


class Relays(RootModel[list[Relay]]):
    root: list[Relay]


class Api4AdminAddAlbumToPowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminAddSongToPowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminChangePowerHourNamePostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminChangePowerHourStartTimePostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminChangePowerHourUrlPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminCreatePowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminDuplicatePowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminEuropifyPowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminJsErrorsPostResponse(BaseModel):
    admin_js_errors: AdminJsErrors


class Api4AdminMusicScanErrorsPostResponse(BaseModel):
    admin_music_scan_errors: AdminMusicScanErrors


class Api4AdminOrderPowerHourSongsPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminPowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminPowerHourRemoveSongPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AdminPowerHoursPostResponse(BaseModel):
    admin_power_hours: AdminPowerHours


class Api4AdminAlbumSongsPostResponse(BaseModel):
    admin_album_songs: AdminAlbumSongs


class Api4AdminAlbumsPostResponse(BaseModel):
    admin_albums: AdminAlbums


class Api4AdminShufflePowerHourPostResponse(BaseModel):
    admin_power_hour: AdminPowerHour


class Api4AllArtistsPostResponse(BaseModel):
    all_artists: AllArtists


class Api4AllArtistsPaginatedPostResponse(BaseModel):
    all_artists_paginated: AllArtistsPaginated


class Api4AllFavesPostResponse(BaseModel):
    all_faves: AllFaves


class Api4AllGroupsPostResponse(BaseModel):
    all_groups: AllGroups


class Api4AllGroupsPaginatedPostResponse(BaseModel):
    all_groups_paginated: AllGroupsPaginated


class Api4AllSongsPostResponse(BaseModel):
    all_songs: AllSongs


class Api4ClearRequestsPostResponse(BaseModel):
    requests: Requests


class Api4ClearRequestsOnCooldownPostResponse(BaseModel):
    requests: Requests


class Api4DeleteRequestPostResponse(BaseModel):
    requests: Requests


class Api4RequestPostResponse(BaseModel):
    requests: Requests


class Api4SongPostResponse(BaseModel):
    song: Song


class Api4StationSongCountPostResponse(BaseModel):
    station_song_count: StationSongCount


class Api4Top100PostResponse(BaseModel):
    top_100: Top100


class Api4UserInfoPostResponse(BaseModel):
    user_info: UserInfo


class Api4UserRecentVotesPostResponse(BaseModel):
    user_recent_votes: UserRecentVotes


class Api4UserRequestedHistoryPostResponse(BaseModel):
    user_requested_history: UserRequestedHistory


class Api4WebsocketSidGetResponse(BaseModel):
    error: Error | None = Field(None, alias='_error')


class AddDonationResult(BooleanResult):
    pass


class AdminAlbumArtModel(RootModel[list[AdminAlbumArt]]):
    root: list[AdminAlbumArt]


class Album(BaseModel):
    added_on: Time
    art: AlbumArt | None
    cool_lowest: Time
    cool: bool
    fave_count: int
    fave: bool
    id: int
    name: str
    played_last: Time
    rating_count: int
    rating_user: RatingUser | None
    rating: float | None
    song_count: int
    vote_count: int
    genres: list[SongGroup]
    rating_complete: bool
    rating_histogram: RatingHistogram
    rating_rank: int
    rating_rank_percentile: int
    request_count: int
    request_rank: int
    request_rank_percentile: int
    songs: list[SongOnAlbum]


class AllAlbums(RootModel[list[AlbumInList]]):
    root: list[AlbumInList]


class AllAlbumsPaginated(BaseModel):
    data: list[AlbumInList]
    has_more: bool
    next: int
    progress: int


class AllStationsInfo(BaseModel):
    field_1: StationInfo = Field(..., alias='1')
    field_2: StationInfo = Field(..., alias='2')
    field_3: StationInfo = Field(..., alias='3')
    field_4: StationInfo = Field(..., alias='4')
    field_5: StationInfo = Field(..., alias='5')
    field_6: StationInfo = Field(..., alias='6')


class DeletePowerHourResult(BooleanResult):
    pass


class EnablePerksByDiscordIdsResult(BooleanResult):
    pass


class FaveAlbumResult(BooleanResult):
    fave: bool
    id: int
    sid: StationId


class FaveAllSongsResult(BooleanResult):
    fave: bool
    sid: StationId
    song_ids: list[int]


class FaveSongResult(BooleanResult):
    fave: bool
    id: int
    sid: StationId


class Group(SongGroup):
    all_songs_for_sid: dict[str, dict[str, list[SongInArtist]]] = Field(
        ..., description='all_songs_for_sid[album_id][station_id] = [song1, song2...]'
    )


class Listener(BaseModel):
    avatar: str | None
    colour: str | None
    losing_votes: int = Field(..., deprecated=True)
    mind_changes: int = Field(..., deprecated=True)
    name: str
    rank: str | None
    rating_spread: list[ListenerRatingSpreadItem]
    ratings_by_station: list[ListenerRatingsByStation]
    ratings_completion: RatingsCompletion
    regdate: Time
    requests_by_source_station: list[ListenerRequestsByStation]
    requests_by_station: list[ListenerRequestsByStation]
    top_albums: list[ListenerTopAlbum]
    top_request_albums: list[ListenerTopRequestAlbum]
    total_ratings: int = Field(..., deprecated=True)
    total_requests: int = Field(..., deprecated=True)
    total_votes: int = Field(..., deprecated=True)
    user_id: int
    votes_by_station: list[ListenerVotesByStation]
    winning_votes: int = Field(..., deprecated=True)


class OrderRequestsResult(RootModel[BooleanResult]):
    root: BooleanResult


class PauseRequestQueueResult(RootModel[BooleanResult]):
    root: BooleanResult


class PlaybackHistory(RootModel[list[PlaybackHistoryEntry]]):
    root: list[PlaybackHistoryEntry]


class RateResult(BooleanResult):
    rating_user: RatingUser | None
    song_id: int
    updated_album_ratings: list[UpdatedAlbumRating]


class RequestFavoritedSongsResult(RootModel[BooleanResult]):
    root: BooleanResult


class RequestLine(RootModel[list[RequestLineEntry]]):
    root: list[RequestLineEntry]


class RequestUnratedSongsResult(RootModel[BooleanResult]):
    root: BooleanResult


class SetAlbumCooldownResult(BooleanResult):
    pass


class SetSongCooldownResult(BooleanResult):
    pass


class SetSongRequestOnlyResult(BooleanResult):
    pass


class Songs(RootModel[list[SearchSong]]):
    root: list[SearchSong]


class Station(BaseModel):
    description: str
    id: StationId
    name: str
    relays: Relays
    stream: str


class Stations(RootModel[list[Station]]):
    root: list[Station]


class UnpauseRequestQueueResult(RootModel[BooleanResult]):
    root: BooleanResult


class UpdateUserAvatarByDiscordIdResult(BooleanResult):
    pass


class UpdateUserNicknameByDiscordIdResult(BooleanResult):
    pass


class VoteResult(BooleanResult):
    elec_id: int | None
    entry_id: int


class AllSongsForArtist(BaseModel):
    field_1: dict[str, list[SongInArtist]] | None = Field(None, alias='1')
    field_2: dict[str, list[SongInArtist]] | None = Field(None, alias='2')
    field_3: dict[str, list[SongInArtist]] | None = Field(None, alias='3')
    field_4: dict[str, list[SongInArtist]] | None = Field(None, alias='4')
    field_5: dict[str, list[SongInArtist]] | None = Field(None, alias='5')
    field_6: dict[str, list[SongInArtist]] | None = Field(None, alias='6')


class Api4AdminAddDonationPostResponse(BaseModel):
    add_donation_result: AddDonationResult


class Api4AdminDeletePowerHourPostResponse(BaseModel):
    delete_power_hour_result: DeletePowerHourResult


class Api4AdminResetAlbumCooldownPostResponse(BaseModel):
    set_album_cooldown_result: SetAlbumCooldownResult


class Api4AdminResetSongCooldownPostResponse(BaseModel):
    set_song_cooldown_result: SetSongCooldownResult


class Api4AdminSetAlbumCooldownPostResponse(BaseModel):
    set_album_cooldown_result: SetAlbumCooldownResult


class Api4AdminSetSongCooldownPostResponse(BaseModel):
    set_song_cooldown_result: SetSongCooldownResult


class Api4AdminSetSongRequestOnlyPostResponse(BaseModel):
    set_song_request_only_result: SetSongRequestOnlyResult


class Api4AdminAlbumArtPostResponse(BaseModel):
    admin_album_art: AdminAlbumArtModel


class Api4UpdateUserAvatarByDiscordIdPostResponse(BaseModel):
    update_user_avatar_by_discord_id_result: UpdateUserAvatarByDiscordIdResult


class Api4UpdateUserNicknameByDiscordIdPostResponse(BaseModel):
    update_user_nickname_by_discord_id_result: UpdateUserNicknameByDiscordIdResult


class Api4EnablePerksByDiscordIdsPostResponse(BaseModel):
    enable_perks_by_discord_ids_result: EnablePerksByDiscordIdsResult


class Api4AlbumPostResponse(BaseModel):
    album: Album


class Api4AllAlbumsPostResponse(BaseModel):
    all_albums: AllAlbums


class Api4AllAlbumsPaginatedPostResponse(BaseModel):
    all_albums_paginated: AllAlbumsPaginated


class Api4ClearRatingPostResponse(BaseModel):
    rate_result: RateResult


class Api4FaveAlbumPostResponse(BaseModel):
    fave_album_result: FaveAlbumResult


class Api4FaveAllSongsPostResponse(BaseModel):
    fave_all_songs_result: FaveAllSongsResult


class Api4FaveSongPostResponse(BaseModel):
    fave_song_result: FaveSongResult


class Api4GroupPostResponse(BaseModel):
    group: Group


class Api4InfoAllPostResponse(BaseModel):
    all_stations_info: AllStationsInfo


class Api4ListenerPostResponse(BaseModel):
    listener: Listener


class Api4OrderRequestsPostResponse(BaseModel):
    order_requests_result: OrderRequestsResult
    requests: Requests


class Api4PauseRequestQueuePostResponse(BaseModel):
    pause_request_queue_result: PauseRequestQueueResult
    user: User


class Api4PlaybackHistoryPostResponse(BaseModel):
    playback_history: PlaybackHistory


class Api4RatePostResponse(BaseModel):
    rate_result: RateResult


class Api4RequestFavoritedSongsPostResponse(BaseModel):
    request_favorited_songs_result: RequestFavoritedSongsResult
    requests: Requests


class Api4RequestLinePostResponse(BaseModel):
    request_line_result: RequestLine


class Api4RequestUnratedSongsPostResponse(BaseModel):
    request_unrated_songs_result: RequestUnratedSongsResult
    requests: Requests


class Api4SearchPostResponse(BaseModel):
    albums: Albums
    artists: Artists
    songs: Songs


class Api4StationsPostResponse(BaseModel):
    stations: Stations


class Api4UnpauseRequestQueuePostResponse(BaseModel):
    unpause_request_queue_result: UnpauseRequestQueueResult
    user: User


class Api4VotePostResponse(BaseModel):
    vote_result: VoteResult


class ArtistModel(Artist):
    all_songs: AllSongsForArtist | None = None


class Api4ArtistPostResponse(BaseModel):
    artist: ArtistModel
