# generated by datamodel-codegen:
#   filename:  rainwave-openapi.json
#   timestamp: 2026-02-21T13:22:20+00:00

from typing import Any, Literal, NotRequired, TypedDict


class AlbumDiffItem(TypedDict):
    id: float
    cool: bool
    cool_lowest: float
    newest_song_time: float


type AlbumDiff = list[AlbumDiffItem]


class AlbumInList(TypedDict):
    id: float
    name: str
    rating: float | None
    cool: bool
    cool_lowest: float
    fave: bool | None
    rating_user: float | None
    rating_complete: bool | None
    newest_song_time: float


class AllAlbumsPaginated(TypedDict):
    data: list[AlbumInList]
    has_next: bool
    next: float
    progress: float


class AllSongsSong(TypedDict):
    album_name: str
    fave: bool | None
    id: float
    rating: float | None
    rating_user: float | None
    title: str


class AllStationsInfo(TypedDict):
    pass


type AlreadyVotedEntry = tuple[float, float]


class ApiInfo(TypedDict):
    exectime: float
    time: float


class Artist(TypedDict):
    id: float
    name: str


class ArtistInList(TypedDict):
    id: float
    name: str
    song_count: float


class BooleanResult(TypedDict):
    success: bool
    tl_key: str
    text: str


type BuildVersion = float


type CookieDomain = str


type DeleteRequestResult = BooleanResult


type ErrorReportResult = BooleanResult


class FaveAlbumResult(TypedDict):
    id: float
    fave: bool
    sid: Literal[1, 2, 3, 4, 5]
    success: bool
    tl_key: str
    text: str


class FaveAllSongsResult(TypedDict):
    song_ids: list[float]
    fave: bool
    sid: Literal[1, 2, 3, 4, 5]
    success: bool
    tl_key: str
    text: str


class FaveSong(TypedDict):
    album_id: float
    album_name: str
    fave: bool | None
    id: float
    rating: float
    rating_user: float | None
    title: str


class FaveSongResult(TypedDict):
    id: float
    fave: bool
    sid: Literal[1, 2, 3, 4, 5]
    success: bool
    tl_key: str
    text: str


class GroupInList(TypedDict):
    id: float
    name: str


class GroupWithDetail(TypedDict):
    id: float
    name: str
    all_songs_for_sid: dict[str, Any]


class ListenerRatingSpreadItem(TypedDict):
    ratings: float
    rating: float


class ListenerRatingsByStation(TypedDict):
    sid: Literal[1, 2, 3, 4, 5]
    average_rating: str
    ratings: float


class ListenerRequestsByStation(TypedDict):
    sid: Literal[1, 2, 3, 4, 5]
    requests: float


class ListenerTopAlbum(TypedDict):
    id: float
    name: str
    rating_listener: float
    rating: float


class ListenerTopRequestAlbum(TypedDict):
    id: float
    name: str
    request_count_listener: float


class ListenerVotesByStation(TypedDict):
    sid: Literal[1, 2, 3, 4, 5]
    votes: float


class LiveVoting(TypedDict):
    pass


type Locale = str


class Locales(TypedDict):
    pass


class MessageId(TypedDict):
    message_id: float


type Mobile = bool


class NativeError(TypedDict):
    name: str
    message: str
    stack: NotRequired[str]


type OnDraw = list[Any]


type OnInit = list[Any]


type OnMeasure = list[Any]


type OrderRequestsResult = BooleanResult


type PauseRequestQueueResult = BooleanResult


class Ping(TypedDict):
    timestamp: float


class PlaybackHistoryEntry(TypedDict):
    album_id: float
    album_name: str
    artist_parseable: str
    fave: bool | None
    id: float
    rating: float
    rating_user: float | None
    song_played_at: float
    title: str


class Pong(TypedDict):
    timestamp: float


class PongConfirm(TypedDict):
    timestamp: float


class RainwaveErrorObject(TypedDict):
    code: float
    tl_key: str
    text: str


class Album1(TypedDict):
    id: float
    name: str
    rating: float | None
    fave: bool | None
    rating_user: float | None
    art: str | None


class RainwaveEventSongArtist(TypedDict):
    order: float
    id: float
    name: str


class RainwaveSdkErrorClear(TypedDict):
    tl_key: str


class RedownloadM3u(TypedDict):
    tl_key: str
    text: str


class Relay(TypedDict):
    name: str
    protocol: str
    hostname: str
    port: float


type Relays = list[Relay]


class RequestAlbum(TypedDict):
    name: str
    id: float
    rating: float | None
    rating_user: float | None
    rating_complete: bool | None
    art: str | None


type RequestFavoritedSongsResult = BooleanResult


class RequestLineEntry(TypedDict):
    username: str
    user_id: float
    line_expiry_tune_in: float | None
    line_expiry_election: float | None
    line_wait_start: float
    line_has_had_valid: bool
    song_id: float | None
    skip: bool
    position: float


type RequestResult = BooleanResult


type RequestUnratedSongsResult = BooleanResult


type SdkErrorClear = RainwaveSdkErrorClear


type SdkException = NativeError


type SdkScheduleSynced = bool


class SearchAlbum(TypedDict):
    id: float
    name: str
    cool: bool
    rating: float | None
    fave: bool | None
    rating_user: float | None
    rating_complete: bool | None


class SearchArtist(TypedDict):
    id: float
    name: str


class SearchSong(TypedDict):
    added_on: float
    album_id: float
    album_name: str
    cool_end: float
    cool: bool
    origin_sid: Literal[1, 2, 3, 4, 5]
    requestable: bool
    id: float
    rating: float
    fave: bool | None
    rating_user: float | None
    title: str
    length: float
    link_text: str | None
    url: str | None


class SongGroup(TypedDict):
    id: float
    name: str


class Album2(TypedDict):
    id: float
    name: str


class SongOnAlbum(TypedDict):
    origin_sid: Literal[1, 2, 3, 4, 5]
    added_on: float
    cool_multiply: NotRequired[float]
    cool_override: NotRequired[float | None]
    requestable: bool
    cool: bool
    cool_end: float
    request_only_end: float
    request_only: bool
    albums: tuple[Album2]
    artists: list[Artist]
    fave: bool | None
    id: float
    length: float
    link_text: str | None
    rating_user: float | None
    rating: float
    title: str
    url: str | None


class AlbumItem(TypedDict):
    id: float
    name: str
    rating: float | None
    fave: bool | None
    rating_user: float | None
    art: str | None
    rating_complete: bool | None


class SongWithDetailArtist(TypedDict):
    order: float
    id: float
    name: str


type Songs = list[SearchSong]


class StationDescription(TypedDict):
    description: str
    id: Literal[1, 2, 3, 4, 5]
    name: str
    relays: Relays
    stream: str


class StationList(TypedDict):
    pass


class StationSongCountByStation(TypedDict):
    sid: Literal[1, 2, 3, 4, 5]
    song_count: float


type Stations = list[StationDescription]


type StreamFilename = str


type SyncResult = RainwaveErrorObject


class Top100Song(TypedDict):
    album_name: str
    id: float
    origin_sid: Literal[1, 2, 3, 4, 5]
    song_rating: float
    song_rating_count: float
    title: str


type UnpauseRequestQueueResult = BooleanResult


class UnratedSong(TypedDict):
    album_name: str
    id: float
    title: str


type UnratedSongs = list[UnratedSong]


class UpdatedAlbumRating(TypedDict):
    sid: Literal[1, 2, 3, 4, 5]
    id: float
    rating_user: float | None
    rating_complete: bool | None


class User(TypedDict):
    admin: bool
    avatar: NotRequired[str | None]
    id: float
    listen_key: str | None
    listener_id: float | None
    lock_counter: float
    lock_in_effect: bool
    lock_sid: float | None
    lock: bool
    name: str
    new_privmsg: float
    perks: bool
    rate_anything: bool
    request_expires_at: float | None
    request_position: float | None
    requests_paused: bool
    sid: Literal[1, 2, 3, 4, 5]
    tuned_in: bool
    voted_entry: float | None


type UserInfo = User


class UserRecentVote(TypedDict):
    album_name: str
    fave: bool | None
    id: float
    rating: float
    rating_user: float | None
    title: str


type UserRecentVotes = list[UserRecentVote]


type UserRequestedHistory = UserRecentVotes


class VoteResult(TypedDict):
    elec_id: float
    entry_id: float
    success: bool
    tl_key: str
    text: str


type WebsocketHost = str


class AlbumWithDetail(TypedDict):
    genres: list[SongGroup]
    rating_complete: bool | None
    rating_rank: float
    rating_rank_percentile: float
    request_count: float
    request_rank: float
    request_rank_percentile: float
    rating_histogram: dict[str, Any]
    songs: list[SongOnAlbum]
    added_on: float
    art: str | None
    cool_lowest: float
    cool_multiply: NotRequired[float]
    cool_override: NotRequired[float | None]
    cool: bool
    fave_count: float
    fave: bool | None
    id: float
    name: str
    played_last: float
    rating_count: float
    rating_user: float | None
    rating: float | None
    song_count: float
    vote_count: float


type Albums = list[SearchAlbum]


class AllArtistsPaginated(TypedDict):
    data: list[ArtistInList]
    has_next: bool
    next: float
    progress: float


type AllFaves = list[FaveSong]


class AllGroupsPaginated(TypedDict):
    data: list[GroupInList]
    has_next: bool
    next: float
    progress: float


type AllSongs = list[AllSongsSong]


type AlreadyVoted = list[AlreadyVotedEntry]


type Artists = list[SearchArtist]


type Error = RainwaveErrorObject


type Group = GroupWithDetail


class Listener(TypedDict):
    user_id: float
    name: str
    avatar: str | None
    colour: str
    rank: str
    total_votes: float
    total_ratings: float
    mind_changes: float
    total_requests: float
    winning_votes: float
    losing_votes: float
    regdate: float
    top_albums: list[ListenerTopAlbum]
    top_request_albums: list[ListenerTopRequestAlbum]
    votes_by_station: list[ListenerVotesByStation]
    requests_by_station: list[ListenerRequestsByStation]
    requests_by_source_station: list[ListenerRequestsByStation]
    ratings_by_station: list[ListenerRatingsByStation]
    ratings_completion: dict[str, Any]
    rating_spread: list[ListenerRatingSpreadItem]


type PlaybackHistory = list[PlaybackHistoryEntry]


class RainwaveEventSong(TypedDict):
    albums: tuple[Album1]
    artists: list[RainwaveEventSongArtist]
    cool: bool
    elec_blocked_by: str | None
    elec_blocked: bool
    elec_request_user_id: float | None
    elec_request_username: str | None
    entry_id: float
    entry_position: float
    entry_type: Literal[2, 4]
    entry_votes: float
    groups: list[SongGroup]
    origin_sid: Literal[1, 2, 3, 4, 5]
    rating_allowed: bool
    rating_count: float
    request_id: NotRequired[float | None]
    request_count: float
    sid: Literal[1, 2, 3, 4, 5]
    fave: bool | None
    id: float
    length: float
    link_text: str | None
    rating_user: float | None
    rating: float
    title: str
    url: str | None


class RateResult(TypedDict):
    updated_album_ratings: list[UpdatedAlbumRating]
    song_id: float
    rating_user: float | None
    success: bool
    tl_key: str
    text: str


class Request(TypedDict):
    albums: tuple[RequestAlbum]
    cool_end: float
    cool: bool
    elec_blocked_by: str | None
    elec_blocked_num: float | None
    elec_blocked: bool
    good: bool
    order: float
    origin_sid: Literal[1, 2, 3, 4, 5]
    request_id: float
    sid: Literal[1, 2, 3, 4, 5]
    valid: bool
    artists: list[Artist]
    fave: bool | None
    id: float
    length: float
    link_text: str | None
    rating_user: float | None
    rating: float
    title: str
    url: str | None


type RequestLine = list[RequestLineEntry]


type Requests = list[Request]


class SongWithDetail(TypedDict):
    album: tuple[AlbumItem]
    artists: list[SongWithDetailArtist]
    cool: bool
    elec_blocked_by: str | None
    elec_blocked: bool
    groups: list[SongGroup]
    origin_sid: Literal[1, 2, 3, 4, 5]
    rating_allowed: bool
    rating_count: float
    rating_rank_percentile: float
    rating_rank: float
    request_count: float
    request_rank_percentile: float
    request_rank: float
    sid: Literal[1, 2, 3, 4, 5]
    albums: tuple[Album2]
    fave: bool | None
    id: float
    length: float
    link_text: str | None
    rating_user: float | None
    rating: float
    title: str
    url: str | None


type StationSongCount = list[StationSongCountByStation]


type Top100 = list[Top100Song]


type Album = AlbumWithDetail


class RainwaveEvent(TypedDict):
    id: float
    start: float
    start_actual: float | None
    end: float
    type: Literal['Election', 'OneUp', 'PVPElection']
    name: str | None
    sid: Literal[1, 2, 3, 4, 5]
    url: str | None
    voting_allowed: bool
    used: bool
    length: float
    core_event_id: float | None
    songs: list[RainwaveEventSong]


type SchedCurrent = RainwaveEvent


type SchedHistory = list[RainwaveEvent]


type SchedNext = list[RainwaveEvent]


type Song = SongWithDetail
