function _svg(icon) {
  const s = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  const u = document.createElementNS('http://www.w3.org/2000/svg', 'use');
  u.setAttributeNS(
    'http://www.w3.org/1999/xlink',
    'xlink:href',
    '/static/images4/symbols.svg#' + icon,
  );
  s.appendChild(u);
  return s;
}
function menu(context) {
  const $rootContext = context;
  const v1 = document.createDocumentFragment();
  const $binds = { $root: v1 };
  const v2 = document.createElement('div');
  v2.className = 'header unselectable';
  $binds['header'] = v2;
  const v3 = document.createElement('div');
  v3.className = 'menu_wrapper';
  $binds['menu_wrapper'] = v3;
  const v4 = document.createElement('ul');
  v4.className = 'menu hamburger_container';
  $binds['hamburger_container'] = v4;
  const v5 = document.createElement('li');
  v5.className = 'hamburger_icon_li';
  v5.appendChild(menu_hamburger(context));
  const v6 = document.createElement('a');
  v6.className = 'link';
  $binds['burger_button'] = v6;
  const v7 = document.createElement('div');
  v7.className = 'hamburger_icon';
  v7.appendChild(v6);
  v6.appendChild(v5);
  v5.appendChild(v4);
  v4.appendChild(v3);
  const v8 = document.createElement('ul');
  v8.className = 'menu user_status';
  if (User.id > 1) {
    const v10 = document.createElement('li');
    $binds['user_link'] = v10;
    v10.className = 'user_info';
    const v11 = document.createElement('a');
    v11.href = '#!/listener/' + User.id;
    const v12 = document.createElement('span');
    v12.appendChild(document.createTextNode(User.name));
    v12.appendChild(v11);
    const v13 = document.createElement('img');
    v13.className = 'avatar';
    v13.setAttribute('src', User.avatar);
    v11.appendChild(v10);
    v10.appendChild(v8);
  } else {
    const v14 = document.createElement('li');
    v14.className = 'login_link';
    const v15 = document.createElement('a');
    $binds['login'] = v15;
    v15.className = 'link';
    v15.href = '/oauth/login';
    v15.appendChild(document.createTextNode($l('login')));
    v15.appendChild(v14);
    v14.appendChild(v8);
    const v16 = document.createElement('li');
    v16.className = 'signup_link';
    const v17 = document.createElement('a');
    v17.href = '/oauth/discord';
    v17.appendChild(document.createTextNode($l('signup')));
    v17.appendChild(v16);
    v16.appendChild(v8);
  }
  v8.appendChild(v3);
  const v18 = document.createElement('ul');
  v18.className = 'menu main_menu';
  $binds['main_menu_ul'] = v18;
  const v19 = document.createElement('li');
  v19.className = 'requests_link';
  const v20 = document.createElement('div');
  $binds['request_indicator'] = v20;
  v20.className = 'plusminus';
  v20.appendChild(v19);
  const v21 = document.createElement('a');
  $binds['request_link'] = v21;
  const v22 = _svg('requests');
  v22.setAttribute('class', 'menu_icon menu_icon_requests');
  v22.appendChild(v21);
  const v23 = document.createElement('span');
  $binds['request_link_text'] = v23;
  v23.appendChild(document.createTextNode($l('Requests')));
  v23.appendChild(v21);
  v21.appendChild(v19);
  v19.appendChild(v18);
  const v24 = document.createElement('li');
  v24.className = 'playlist_link';
  const v25 = document.createElement('a');
  $binds['playlist_link'] = v25;
  const v26 = _svg('library');
  v26.setAttribute('class', 'menu_icon menu_icon_library');
  v26.appendChild(v25);
  const v27 = document.createElement('span');
  v27.appendChild(document.createTextNode($l('library')));
  v27.appendChild(v25);
  v25.appendChild(v24);
  v24.appendChild(v18);
  const v28 = document.createElement('li');
  v28.className = 'search_link';
  const v29 = document.createElement('a');
  $binds['search_link'] = v29;
  const v30 = document.createElement('img');
  v30.className = 'menu_icon menu_icon_search';
  v30.setAttribute('src', '/static/images4/search.png');
  const v31 = document.createElement('span');
  v31.appendChild(document.createTextNode($l('search')));
  v31.appendChild(v29);
  v29.appendChild(v28);
  v28.appendChild(v18);
  v18.appendChild(v3);
  const v32 = document.createElement('div');
  v32.setAttribute('id', 'station_select');
  $binds['station_select'] = v32;
  v32.className = 'closed';
  const v33 = _svg('pulldown');
  $binds['pulldown'] = v33;
  v33.setAttribute('class', 'pulldown_arrow');
  v33.appendChild(v32);
  const v34 = document.createElement('a');
  v34.setAttribute('id', 'station_select_header');
  $binds['station_select_header'] = v34;
  v34.className = 'station';
  const v35 = document.createElement('div');
  v35.className = 'station_details';
  const v36 = document.createElement('div');
  v36.className = 'station_name';
  v36.appendChild(document.createTextNode($l('station_select_header')));
  v36.appendChild(v35);
  v35.appendChild(v34);
  v34.appendChild(v32);
  function v37Loop(context) {
    const $rootContext = context;
    const v37 = document.createDocumentFragment();
    const $binds = { $root: v37 };
    const v38 = document.createElement('a');
    $binds['menu_link'] = v38;
    v38.className = 'station';
    if (_c.id != User.sid && !MOBILE) {
      const v40 = document.createElement('div');
      $binds['menu_np'] = v40;
      v40.className = 'station_song_container';
      const v41 = document.createElement('div');
      $binds['menu_np_art'] = v41;
      v41.className = 'ss_art';
      v41.appendChild(v40);
      const v42 = document.createElement('div');
      $binds['menu_np_song'] = v42;
      v42.className = 'ss_title';
      v42.appendChild(v40);
      const v43 = document.createElement('div');
      $binds['menu_np_album'] = v43;
      v43.className = 'ss_album';
      v43.appendChild(v40);
      v40.appendChild(v38);
    }
    const v44 = document.createElement('div');
    v44.className = 'station_details';
    const v45 = document.createElement('div');
    v45.className = 'station_name';
    v45.appendChild(document.createTextNode(context.name));
    v45.appendChild(v44);
    const v46 = document.createElement('div');
    v46.className = 'station_description';
    v46.appendChild(document.createTextNode($l('station_menu_description_id_' + _c.id)));
    v46.appendChild(v44);
    v44.appendChild(v38);
    v38.appendChild(v32);
  }
  $binds.stations = context.stations.map((v37Each) => {
    const $r = v37Loop(v37Each);
    v32.appendChild($r.$root);
    return $binds;
  });
  v32.appendChild(v3);
  const v47 = document.createElement('div');
  v47.setAttribute('id', 'r4_audio_player');
  $binds['player'] = v47;
  v47.className = 'unselectable';
  const v48 = document.createElement('div');
  v48.className = 'load_indicator';
  v48.appendChild(v47);
  const v49 = document.createElement('div');
  v49.className = 'tuned_in_indicator';
  v49.appendChild(v47);
  const v50 = document.createElement('div');
  v50.className = 'm3u menu_dropdown menu_hover_dropdown pconly';
  const v51 = document.createElement('a');
  $binds['play2'] = v51;
  v51.className = 'link';
  v51.appendChild(document.createTextNode($l('listen_via_browser')));
  v51.appendChild(v50);
  const v52 = document.createElement('a');
  v52.href = '/tune_in/' + User.sid + '.mp3.m3u';
  v52.setAttribute('target', '_blank');
  v52.appendChild(document.createTextNode($l('listen_via_mp3')));
  v52.appendChild(v50);
  const v53 = document.createElement('a');
  v53.href = '/tune_in/' + User.sid + '.ogg.m3u';
  v53.setAttribute('target', '_blank');
  v53.appendChild(document.createTextNode($l('listen_via_ogg')));
  v53.appendChild(v50);
  v50.appendChild(v47);
  const v54 = document.createElement('div');
  v54.className = 'background';
  const v55 = _svg('play');
  $binds['play'] = v55;
  v55.setAttribute('class', 'audio_icon audio_icon_play');
  v55.appendChild(v54);
  const v56 = _svg('stop');
  $binds['stop'] = v56;
  v56.setAttribute('class', 'audio_icon audio_icon_stop pconly');
  v56.appendChild(v54);
  const v57 = _svg('mute');
  $binds['mute'] = v57;
  v57.setAttribute('class', 'audio_icon audio_icon_mute pconly');
  v57.appendChild(v54);
  v54.appendChild(v47);
  v47.appendChild(v3);
  v3.appendChild(v2);
  v2.appendChild(v1);
  return $binds;
}
export default { menu };
